// 2026-08-25: Napi igék + bátorító üzenetek — MÁSODIK FÉLÉV (júl. 1. – dec. 31., 184 nap).
//
// Célközönség: a Kartotékát használó egyházi munkatársak (lelkipásztorok,
// adminisztrátorok, könyvelők, gondnokok) az Erdélyi Református Egyházkerületben.
// Az igehelyek a Károli-fordítás fejezet-/versszámozása szerintiek; minden
// hivatkozást a @kartoteka/biblia validateReference ellenőriz a selftestben.
//
// Szezonalitás: júl–aug. pihenés/megújulás/teremtés (táborok, VBH), aug. 20.
// környéke új kenyér; szept. újrakezdés/tanévkezdés/vallásóra; okt. a reformáció
// hónapja (okt. 31. emléknap); nov. az örök élet reménye + hálaadás (halottak
// napja környékén vigasztalás); dec. advent, karácsony (12-24–26), óév (12-31).

import type { NapiIgeNaptar } from './napi-ige-types'

export const NAPI_IGEK_2FELEV: NapiIgeNaptar = {
  // ── JÚLIUS — pihenés, megújulás, teremtés, táborok ideje ──────────────────
  '07-01': { ige: 'Zsolt 121,1-2', uzenet: 'A félév első napján emeljük fel tekintetünket: segítségünk nem a körülményekből, hanem az ég és föld Teremtőjétől érkezik.' },
  '07-02': { ige: 'Mt 11,28', uzenet: 'Ha az év első fele elfárasztott, ez a hívás személyesen szól: Jézusnál nem teljesítményt kell letenni, hanem terhet. Merjük elfogadni a pihenést.' },
  '07-03': { ige: 'Zsolt 23,2-3', uzenet: 'A jó Pásztor nemcsak munkába küld, hanem füves legelőkre is terel. A nyári csendben hadd üdítse fel a lelkünket is.' },
  '07-04': { ige: '1Móz 2,2-3', uzenet: 'Maga a Teremtő szentelte meg a megpihenés napját. A szünet nem lustaság: Isten rendje, amely minket is véd és gyógyít.' },
  '07-05': { ige: 'Mk 6,31', uzenet: 'Jézus a tanítványait is elhívta egy csendes helyre. A táborok és csendeshetek szervezésének fáradsága mögött ott a meghívás nekünk is: pihenjünk meg nála.' },
  '07-06': { ige: 'Zsolt 19,2', uzenet: 'Egy nyári csillagos ég többet mond Isten nagyságáról, mint sok érvelés. Ma este érdemes felnézni és rácsodálkozni kezei munkájára.' },
  '07-07': { ige: 'Ézs 40,31', uzenet: 'Nem a fiatalság, hanem az Úrban való bizalom újítja meg az erőt. Akik benne reménykednek, szárnyra kelnek — a sokadik szolgálati év után is.' },
  '07-08': { ige: 'Zsolt 8,4-5', uzenet: 'A teremtett világ hatalmas, mégis az embert koronázta meg Isten a figyelmével. Ma minket is számon tart — név szerint.' },
  '07-09': { ige: 'Jn 15,5', uzenet: 'A gyümölcs nem erőlködésből, hanem kapcsolatból terem. Maradjunk ma is a Szőlőtőn — a növekedés az ő dolga.' },
  '07-10': { ige: '1Móz 1,31', uzenet: 'Isten megnézte, amit alkotott, és igen jónak látta. Szabad nekünk is megállni, és örülni annak, ami elkészült.' },
  '07-11': { ige: 'Zsolt 46,11', uzenet: '„Csendesedjetek el" — ez nem javaslat, hanem gyógyszer. A nyár közepén hagyjunk időt arra, hogy Isten Isten lehessen a gondjaink felett is.' },
  '07-12': { ige: 'Mt 6,26', uzenet: 'Az égi madarak nem vezetnek készletnyilvántartást, Atyánk mégis táplálja őket. Mennyivel inkább gondoskodik rólunk, akik rá bízzuk magunkat.' },
  '07-13': { ige: 'Zsolt 127,2', uzenet: 'A zsoltár szerint szerelmesének álmában ad eleget az Úr. Az alvás is lehet istentisztelet: a bizalom csendes kifejezése.' },
  '07-14': { ige: '5Móz 33,27', uzenet: 'Alattunk örökkévaló karok tartanak. Amikor elfogy a saját erőnk, nem a mélybe zuhanunk, hanem Isten hűségébe.' },
  '07-15': { ige: 'Mk 10,14', uzenet: 'A gyermekhetek hangzavara Jézus fülének kedves zene. Aki most VBH-t szervez vagy gyermekek közt szolgál, a Mester hívását teljesíti.' },
  '07-16': { ige: 'Zsolt 78,4', uzenet: 'Amit mi hallottunk az atyáktól, továbbadjuk a következő nemzedéknek. Minden tábori énekben és bibliai történetben ez a lánc folytatódik.' },
  '07-17': { ige: 'Préd 3,1', uzenet: 'Mindennek rendelt ideje van: a munkának és a megállásnak is. Ne bűntudattal töltsük a szabadságot — az is Istentől rendelt idő.' },
  '07-18': { ige: 'Zsolt 104,24', uzenet: 'Milyen számtalanok az Úr művei! Egy nyári kirándulás is lehet istentisztelet, ha nyitott szemmel járjuk a teremtett világot.' },
  '07-19': { ige: 'Jn 7,37', uzenet: 'A nyári hőségben jólesik a hideg víz — Jézus a szomjazó léleknek kínál élő vizet. Jöjjünk hozzá ma is meríteni.' },
  '07-20': { ige: 'Péld 22,6', uzenet: 'Amit egy gyermek most tanul a hitről, felnőttként is elkíséri. A táborokban elvetett mag évtizedek múlva is teremhet.' },
  '07-21': { ige: 'Zsolt 42,2', uzenet: 'Ahogy a szarvas a hűs patakra, úgy vágyik a lélek Istenre. A szomjúság nem hiba: jel, amely a forráshoz vezet.' },
  '07-22': { ige: 'Ézs 55,10-11', uzenet: 'Az eső sem tér vissza dolgavégezetlenül — Isten beszéde sem. Amit a nyáron hirdettünk és tanítottunk, nem vész el.' },
  '07-23': { ige: 'Mt 5,14-16', uzenet: 'A hegyen épült város nem rejthető el. Az ifjúsági héten, a faluban, a hivatalban: világosságunk másokért ég.' },
  '07-24': { ige: 'Zsolt 133,1', uzenet: 'Milyen jó, amikor a testvérek együtt lakoznak — egy tábortűz mellett, egy asztalnál, egy gyülekezetben. A közösség Isten ajándéka.' },
  '07-25': { ige: 'JSir 3,22-23', uzenet: 'Minden reggel újak az Úr irgalmai. A tegnapi kudarcot nem kell áthozni a mai napba: hűsége nagyobb a mulasztásainknál.' },
  '07-26': { ige: '1Sám 3,10', uzenet: '„Szólj, mert hallja a te szolgád" — Sámuel válasza ma is időszerű. A csendesebb nyári napok jó alkalmak a figyelmes hallgatásra.' },
  '07-27': { ige: 'Zsolt 145,9', uzenet: 'Jó az Úr mindenkihez: a fáradthoz, a kételkedőhöz, az újrakezdőhöz is. Az ő könyörülete ma is ránk hajol.' },
  '07-28': { ige: 'Kol 3,23', uzenet: 'Amit teszünk, lélekből tegyük — a nyári karbantartást, a levelezést, a legkisebb ügyintézést is. Az Úrnak végzett munka sosem jelentéktelen.' },
  '07-29': { ige: 'Zsolt 36,10', uzenet: 'Istennél van az élet forrása. Amikor kiszáradunk, ne a magunk kútjait mélyítsük tovább — térjünk vissza hozzá.' },
  '07-30': { ige: '2Móz 33,14', uzenet: 'Isten jelenléte a nyugalom titka: az ő orcája jár a népével. Vele még a terhelt napok is hordozhatóvá szelídülnek.' },
  '07-31': { ige: 'Zsolt 90,1-2', uzenet: 'Nemzedékről nemzedékre az Úr volt népének hajléka. A hónap zártával mi is ebben a biztos hajlékban hajthatjuk le a fejünket.' },

  // ── AUGUSZTUS — megújulás, gondviselés, új kenyér ─────────────────────────
  '08-01': { ige: 'Zsolt 34,9', uzenet: 'Érezzétek és lássátok, hogy jó az Úr! Az ő jósága nem elmélet: megkóstolható a mindennapokban, a legkisebb gondviselésben is.' },
  '08-02': { ige: 'Ézs 43,1', uzenet: 'Nevünkön szólított és megváltott — nem vagyunk névtelen munkatársak Isten országában. A félelem helyét ma a hozzátartozás öröme veheti át.' },
  '08-03': { ige: 'Zsolt 62,2', uzenet: 'Csak Istenben nyugszik meg a lélek. Sok minden ígér pihenést a nyáron, de a mély megnyugvás egyedül nála található.' },
  '08-04': { ige: 'Mk 4,26-27', uzenet: 'A mag akkor is nő, amikor a gazda alszik. A tavasszal és nyáron elvetett ige dolgozik — akkor is, amikor mi éppen megpihenünk.' },
  '08-05': { ige: 'Zsolt 84,11', uzenet: 'Jobb egy nap Isten tornácaiban, mint ezer másutt. A vasárnapi istentisztelet nem kötelesség a naptárban, hanem a hét legjobb órája.' },
  '08-06': { ige: 'Fil 4,6-7', uzenet: 'Az aggodalmat imádsággá lehet alakítani: ez a csere mindig megéri. Isten békessége pedig őrzi a szívet — mint egy hűséges őrség.' },
  '08-07': { ige: 'Zsolt 139,9-10', uzenet: 'A hajnal szárnyán, a tenger túlsó szélén is az ő keze vezet. Úton, távol az otthontól sem utazunk ki Isten jelenlétéből.' },
  '08-08': { ige: 'Préd 4,9-10', uzenet: 'Jobban boldogul kettő, mint egy: ha elesnek, felemeli egyik a társát. A szolgálatban sem magányos hősökre, hanem testvérekre van szükség.' },
  '08-09': { ige: 'Jn 14,27', uzenet: 'Jézus békessége nem olyan, mint amit a világ ad: nem a körülményektől függ. Ma is elfogadhatjuk — akár nyugtalan szívvel is.' },
  '08-10': { ige: 'Zsolt 16,11', uzenet: 'Isten megismerteti velünk az élet ösvényét, és színe előtt teljes az öröm. A vele járt út nem szürke kötelesség, hanem örömforrás.' },
  '08-11': { ige: '1Kir 19,12', uzenet: 'Illés nem a szélben és nem a tűzben, hanem a halk, szelíd hangban találkozott Istennel. A csendes órákat ne engedjük ki a kezünkből.' },
  '08-12': { ige: 'Zsolt 100,2', uzenet: 'Szolgáljatok az Úrnak örvendezéssel! A szolgálat hangneme nem mellékes: az öröm nem ráadás, hanem a hitelesség része.' },
  '08-13': { ige: 'Róm 8,28', uzenet: 'Azoknak, akik Istent szeretik, minden javukra van — a kitérők és a késések is. Ő a görbe vonalakon is egyenesen ír.' },
  '08-14': { ige: 'Zsolt 103,2', uzenet: 'Áldjad, én lelkem, az Urat, és ne feledd el jótéteményeit! Érdemes ma listát írni: miből őrzött meg, mit adott, mit gyógyított.' },
  '08-15': { ige: 'Mt 6,28-29', uzenet: 'A mezők liliomai nem szőnek és nem fonnak, mégis felülmúlják Salamon pompáját. A gondviselés nem érdemeink jutalma, hanem Atyánk természete.' },
  '08-16': { ige: 'Zsolt 92,2', uzenet: 'Jó dolog dicsérni az Urat — a zsoltár szerint ez egyszerűen jó. A hála nem kötelező kör, hanem felszabadító életforma.' },
  '08-17': { ige: 'Zsolt 65,10', uzenet: 'Isten meglátogatja a földet és megöntözi — az érő termés az ő hűségének látható jele. A betakarítás ideje hálára hangolhatja a szívünket.' },
  '08-18': { ige: 'Jak 1,17', uzenet: 'Minden jó adomány felülről száll alá a világosság Atyjától, akiben nincs változás. Ajándékai mögött maga az Ajándékozó a legnagyobb kincs.' },
  '08-19': { ige: '5Móz 8,3', uzenet: 'Nemcsak kenyérrel él az ember. A testi kenyérért dolgozunk — az igéért csak le kell ülni és venni. Ma se maradjon el ez az étkezés.' },
  '08-20': { ige: 'Jn 6,35', uzenet: 'Az új kenyér ünnepe felé valljuk: Jézus az élet kenyere. Aki hozzá megy, nem éhezik meg — asztala minden gyülekezetben terítve van.' },
  '08-21': { ige: 'Zsolt 145,15-16', uzenet: 'Minden szem rá vigyáz, és ő idejében ad eledelt. Megnyitja kezét — a mi dolgunk csak annyi, hogy a magunkét ne szorítsuk ökölbe.' },
  '08-22': { ige: '2Kor 9,10', uzenet: 'Aki magot ad a magvetőnek és kenyeret az evőnek, a mi szolgálatunk vetőmagját is megszaporítja. Adni nála sosem veszteség.' },
  '08-23': { ige: 'Zsolt 37,5', uzenet: 'Hagyjad az Úrra utadat, bízzál benne, és ő megcselekszi. A ránk bízott ügyek mögött áll valaki, aki nálunk hűségesebben viszi őket.' },
  '08-24': { ige: 'Ézs 26,3', uzenet: 'Akinek szíve az Úrra támaszkodik, azt teljes békében őrzi meg. A béke nem a problémák hiánya, hanem a támaszték szilárdsága.' },
  '08-25': { ige: 'Zsolt 118,24', uzenet: 'Ez a nap az, amelyet az Úr rendelt — nem a holnapi és nem a tegnapi. Örvendezzünk ma, itt, ebben a szolgálatban.' },
  '08-26': { ige: '1Pt 5,7', uzenet: 'Minden gondunkat őrá vethetjük — nem csak a nagyokat. Akire a világmindenség tartozik, annak ránk is személyesen gondja van.' },
  '08-27': { ige: 'Zsolt 116,7', uzenet: 'Térj vissza, lelkem, nyugalmadba, mert az Úr jót tett veled. A nyár végén jó számba venni: valóban jót tett — van hová visszatérnünk.' },
  '08-28': { ige: 'Ef 3,20', uzenet: 'Isten mérhetetlenül többet tud tenni, mint amit kérni vagy elgondolni merünk. Az őszi terveket ezzel a bátorsággal érdemes szőni.' },
  '08-29': { ige: 'Zsolt 143,8', uzenet: '„Add, hogy reggel kegyelmedet halljam" — imádkozta Dávid. A nap első perceinek iránya sokszor az egész napot eldönti.' },
  '08-30': { ige: 'Péld 3,5-6', uzenet: 'Teljes szívből bízzunk az Úrban, és ne a magunk eszére támaszkodjunk. Aki minden útján őt ismeri el, annak ösvényét ő egyengeti.' },
  '08-31': { ige: 'Zsolt 90,17', uzenet: '„Kezünk munkáját tedd állandóvá!" — kéri a zsoltár. A nyár lezárultával kérjük ezt az áldást az induló munkaév minden feladatára.' },

  // ── SZEPTEMBER — újrakezdés, tanévkezdés, vallásóra ───────────────────────
  '09-01': { ige: 'Ézs 43,19', uzenet: '„Ímé, újat cselekszem" — mondja az Úr a tanév és a munkaév küszöbén. Nem a régi kudarcok folytatása vár ránk, hanem az ő új kezdete.' },
  '09-02': { ige: 'Zsolt 25,4-5', uzenet: '„Útjaidat, Uram, ismertesd meg velem" — jó imádság ez tanulónak és tanítónak egyaránt. A szeptember nekünk is a tanulás hónapja lehet.' },
  '09-03': { ige: 'Péld 1,7', uzenet: 'Az Úr félelme a bölcsesség kezdete. A vallásórákon nem tananyagot adunk át, hanem ennek a bölcsességnek az első lépéseit.' },
  '09-04': { ige: '5Móz 6,6-7', uzenet: 'Az igét otthon, útközben, este és reggel kell továbbadni — így szól a régi parancs. A hitre nevelés nem óraszám kérdése, hanem életforma.' },
  '09-05': { ige: 'Zsolt 119,105', uzenet: 'Lámpás az ige a lábunk előtt: nem az egész utat világítja be, csak a következő lépést. Ennyi viszont minden nap elég.' },
  '09-06': { ige: '2Tim 1,7', uzenet: 'Nem a félelem lelkét kaptuk, hanem az erő, a szeretet és a józanság lelkét. Az új tanév kihívásai előtt ez a hármas a felszerelésünk.' },
  '09-07': { ige: 'Zsolt 32,8', uzenet: '„Bölccsé teszlek, és megtanítalak, melyik úton járj" — ígéri az Úr. Nem térkép nélkül indulunk az őszbe: a szemével tanácsol minket.' },
  '09-08': { ige: 'Neh 8,10', uzenet: 'Amikor a nép sírva hallgatta a törvényt, Nehémiás így bátorította őket: az Úr öröme a ti erősségetek. A miénk is — ma is.' },
  '09-09': { ige: 'Fil 1,6', uzenet: 'Aki elkezdte bennünk a jó munkát, be is fejezi. Ez a gyülekezet minden tagjára igaz — a legreménytelenebbnek látszóra is.' },
  '09-10': { ige: 'Zsolt 127,1', uzenet: 'Ha az Úr nem építi a házat, hiába fáradnak az építők. Az őszi tervek, programok, órarendek előtt először őt hívjuk az építkezéshez.' },
  '09-11': { ige: 'Jak 1,5', uzenet: 'Ha valakinek nincs bölcsessége, kérje Istentől, aki szemrehányás nélkül ad mindenkinek. Kérdéseinkkel nem terheljük — megtiszteljük őt.' },
  '09-12': { ige: 'Zsolt 86,11', uzenet: '„Taníts engem utadra, hogy igazságodban járjak, és tedd egyenessé szívemet!" Egy szívvel, nem megosztottan — így lehet igazán tanulni és szolgálni.' },
  '09-13': { ige: 'Mt 6,33', uzenet: 'Keressük először Isten országát, és a többi megadatik. A szeptemberi sokféle teendő között ez a sorrend tart meg minket.' },
  '09-14': { ige: 'Kol 3,16', uzenet: 'Krisztus beszéde lakjék bennünk gazdagon — ne csak vendégeskedjen. A rendszeres igeolvasás az őszi újrakezdés legjobb szokása.' },
  '09-15': { ige: 'Józs 1,9', uzenet: 'Légy bátor és erős! Ne félj és ne rettegj, mert veled van az Úr, ahová csak mégy — az új osztályterembe és az új feladatba is.' },
  '09-16': { ige: 'Péld 16,3', uzenet: 'Bízzad az Úrra dolgaidat, és teljesülnek szándékaid. A határidőnaplónk minden bejegyzése elfér az ő kezében.' },
  '09-17': { ige: 'Zsolt 19,8', uzenet: 'Az Úr törvénye tökéletes: megeleveníti a lelket, és bölccsé teszi az egyszerű embert. Nem kell tudósnak lenni — csak nyitott szívűnek.' },
  '09-18': { ige: '1Kor 15,58', uzenet: 'Munkátok nem hiábavaló az Úrban. A be nem számolt órák, a láthatatlan hűség — mind számon van tartva odafenn.' },
  '09-19': { ige: 'Zsolt 71,17', uzenet: '„Istenem, gyermekségemtől fogva tanítottál engem" — vallja a zsoltáros. Akik ma gyermekeket tanítanak, évtizedekre szóló hálát alapoznak meg.' },
  '09-20': { ige: 'Ézs 40,29', uzenet: 'Erőt ad a megfáradtnak, és az erőtlen erejét megsokasítja. A szeptemberi hajrában nem a saját tartalékainkra vagyunk utalva.' },
  '09-21': { ige: 'Zsolt 1,1-3', uzenet: 'A folyóvíz mellé ültetett fa idejében terem — nem siettetve, nem kényszerítve. A gyökerek táplálása most is fontosabb, mint a látványos lomb.' },
  '09-22': { ige: 'Gal 6,9', uzenet: 'A jó cselekvésében ne fáradjunk el, mert a maga idejében aratunk, ha el nem lankadunk. Az ősz az állhatatosság évszaka.' },
  '09-23': { ige: 'Préd 11,6', uzenet: 'Reggel vesd el magodat, és este se pihentesd kezedet — nem tudni, melyik hajtás ered meg. A hűséges vetés a mi részünk, a növekedés az Úré.' },
  '09-24': { ige: 'Ézs 50,4', uzenet: 'Az Úr bölcs nyelvet ad, hogy szavainkkal erősíteni tudjuk a megfáradtat. Ma valakinek éppen a mi bátorító mondatunkra van szüksége.' },
  '09-25': { ige: 'Zsolt 34,12', uzenet: '„Jöjjetek, fiaim, hallgassatok rám, az Úr félelmére tanítalak titeket." A vallásóra ennek az ősi meghívásnak a mai folytatása.' },
  '09-26': { ige: 'Róm 12,2', uzenet: 'Ne igazodjunk a világhoz, hanem változzunk el értelmünk megújulásával. A megújulás nem egyszeri élmény, hanem naponkénti formálódás.' },
  '09-27': { ige: 'Zsolt 143,10', uzenet: 'Taníts engem akaratod teljesítésére, mert te vagy Istenem! A legfontosabb tantárgy nem az iskolapadban tanulható.' },
  '09-28': { ige: 'Mt 7,24-25', uzenet: 'A kősziklára épített ház kiállta az esőt, az árvizet és a szelet. Az ige hallása és megtartása — ez az alapozás munkája bennünk.' },
  '09-29': { ige: '2Tim 2,15', uzenet: 'Álljunk meg Isten előtt megbízható munkásként, aki helyesen hasogatja az igazság beszédét. A készülés — prédikációra, órára — szent munka.' },
  '09-30': { ige: '2Pt 3,18', uzenet: 'Növekedjünk a kegyelemben és Urunk ismeretében! Egy hónapnyi újrakezdés után is ez marad az irány: nem teljesíteni, hanem növekedni.' },

  // ── OKTÓBER — a reformáció hónapja: az Ige és a kegyelem ──────────────────
  '10-01': { ige: 'Zsolt 119,89', uzenet: 'Örökké megmarad igéd, Uram, a mennyben. A reformáció hónapját kezdve erre az el nem múló szóra építünk mindent.' },
  '10-02': { ige: 'Róm 1,16-17', uzenet: 'Nem szégyelljük az evangéliumot: Isten ereje az minden hívő üdvösségére. Ez a mondat egykor egyházat újított meg — ma minket újíthat.' },
  '10-03': { ige: 'Zsolt 33,4', uzenet: 'Az Úr szava igaz, és minden cselekedete hűséges. Amire ő mond igent, az áll — akkor is, ha körülöttünk minden inog.' },
  '10-04': { ige: 'Ef 2,8-9', uzenet: 'Kegyelemből, hit által van üdvösségünk — nem cselekedetekből, hogy senki se kérkedjék. A reformáció szíve ma is ez a felszabadító hír.' },
  '10-05': { ige: 'Zsolt 18,3', uzenet: 'Kőszikla, vár, szabadító — így ismerte Dávid az Urat. A mi bizalmunk is ilyen konkrét lehet: nem eszmében, hanem személyben bízunk.' },
  '10-06': { ige: 'Jn 8,31-32', uzenet: 'Ha megmaradunk Jézus beszédében, megismerjük az igazságot, és az igazság szabaddá tesz. A szabadság nála nem szólam, hanem napi tapasztalat.' },
  '10-07': { ige: '2Tim 3,16-17', uzenet: 'A teljes Írás Istentől ihletett, és hasznos a tanításra és a nevelésre. A kezünkben lévő Biblia a szolgálatunk legfőbb munkaeszköze.' },
  '10-08': { ige: 'Zsolt 62,7-8', uzenet: 'Csak ő a kősziklám és szabadulásom — nem rendülök meg. A „csak" a zsoltár kulcsszava: nem Isten és valami más, hanem egyedül ő.' },
  '10-09': { ige: 'Róm 5,1', uzenet: 'Mivel hit által igazultunk meg, békességünk van Istennel. Nem fegyverszünet ez, hanem helyreállt kapcsolat — Krisztus érdeméért.' },
  '10-10': { ige: 'Ézs 40,8', uzenet: 'Megszárad a fű, elhull a virág — de Istenünk beszéde mindörökre megmarad. Az őszi hervadás évszakában ez a maradandóság a vigaszunk.' },
  '10-11': { ige: 'Zsid 4,12', uzenet: 'Isten beszéde élő és ható, élesebb minden kétélű kardnál. Nem mi tartjuk életben az igét — az ige tart életben minket.' },
  '10-12': { ige: 'Zsolt 71,3', uzenet: 'Légy sziklaváram, ahova mindenkor mehetek! Isten nem alkalmi menedék: ajtaja hivatali időn kívül is nyitva áll.' },
  '10-13': { ige: 'Gal 5,1', uzenet: 'Krisztus szabadságra szabadított meg minket — álljunk meg hát ebben. A reformátorok öröksége: se törvényeskedés, se szabadosság, hanem hála.' },
  '10-14': { ige: 'Jer 15,16', uzenet: 'Jeremiás „megette" Isten szavait, és azok szíve örömévé váltak. A napi ige is így válhat táplálékká — nem elég nézni, be kell fogadni.' },
  '10-15': { ige: 'Mt 24,35', uzenet: 'Az ég és a föld elmúlnak, de Jézus beszédei semmiképpen el nem múlnak. Minden más alapunk ideiglenes — ez az egy örök.' },
  '10-16': { ige: 'Zsolt 130,5', uzenet: 'Várom az Urat, várja az én lelkem, és bízom ígéretében. A várakozás nem tétlenség: az ígéretbe kapaszkodó remény munkája.' },
  '10-17': { ige: 'Róm 10,17', uzenet: 'A hit hallásból van, a hallás pedig Isten igéje által. Minden istentisztelet és minden bibliaóra hit születésének lehetséges helye.' },
  '10-18': { ige: 'Jak 1,22', uzenet: 'Az igének megtartói legyünk, ne csak hallgatói. A vasárnapi üzenet hétfőn válik igazán prédikációvá — a tetteinkben.' },
  '10-19': { ige: 'Zsolt 56,4', uzenet: '„Mikor félnem kellene is, én bízom benned" — mondja a zsoltáros. A bátorság nem a félelem hiánya, hanem a bizalom többlete.' },
  '10-20': { ige: '5Móz 31,8', uzenet: 'Az Úr maga megy előtted, ő lesz veled: nem hagy el téged. Az új feladat kapuján nem elsőként lépünk be — ő már odabent vár.' },
  '10-21': { ige: 'Lk 11,28', uzenet: 'Boldogok, akik hallgatják és megtartják Isten beszédét. Ez a boldogság nem hangulat kérdése: az engedelmesség csendes gyümölcse.' },
  '10-22': { ige: 'Zsolt 94,19', uzenet: 'Mikor megsokasodtak bennem aggódásaim, vigasztalásaid megvidámították lelkemet. Isten nem a gondjaink számát nézi — a szívünkhöz hajol le.' },
  '10-23': { ige: '1Kor 3,11', uzenet: 'Más alapot senki sem vethet a meglévőn kívül, amely a Jézus Krisztus. Épületeink és programjaink megújulhatnak — az alap nem cserélhető.' },
  '10-24': { ige: 'Hab 2,4', uzenet: 'Az igaz ember az ő hite által él — ez a rövid mondat gyújtotta lángra a reformációt. Ma is elég egyetlen ige, hogy életek forduljanak meg.' },
  '10-25': { ige: 'Péld 30,5', uzenet: 'Istennek teljes beszéde igen tiszta, és pajzs az ahhoz folyamodóknak. Az ige nemcsak világít: védelmez is.' },
  '10-26': { ige: 'Kol 2,6-7', uzenet: 'Ahogy befogadtuk Krisztust, úgy járjunk is őbenne: meggyökerezve és épülve. A hit nem múzeumi örökség, hanem élő növekedés.' },
  '10-27': { ige: 'Zsolt 27,1', uzenet: 'Az Úr az én világosságom és üdvösségem: kitől féljek? A rövidülő őszi napokban is van kiapadhatatlan fényforrásunk.' },
  '10-28': { ige: 'Jn 17,17', uzenet: '„Szenteld meg őket a te igazságoddal: a te igéd igazság" — imádkozta Jézus értünk is. Az ige formál minket, miközben mi az igét hirdetjük.' },
  '10-29': { ige: 'Ézs 12,2', uzenet: 'Íme, Isten az én szabadítóm: bízom és nem félek! Az üdvösség öröme nem a kezdők lelkesedése — a megtartottak józan bizonyossága.' },
  '10-30': { ige: 'Róm 8,31', uzenet: 'Ha Isten velünk, kicsoda ellenünk? A reformátorok ebből a mondatból merítettek bátorságot — kisebbségben, ellenszélben is.' },
  '10-31': { ige: 'Zsolt 46,2-3', uzenet: 'Erős vár a mi Istenünk! A reformáció emléknapján valljuk elődeinkkel: nem félünk, ha a föld megindul is — oltalmunk és erősségünk ő.' },

  // ── NOVEMBER — az örök élet reménye, vigasztalás, hálaadás ────────────────
  '11-01': { ige: 'Jn 11,25-26', uzenet: '„Én vagyok a feltámadás és az élet" — Jézus szava a temetők csendjében is érvényes. Aki benne hisz, ha meghal is, él.' },
  '11-02': { ige: 'Zsolt 116,15', uzenet: 'Az Úr szemei előtt drága az ő kegyeseinek halála. Akiket elengedtünk, nem elvesztek — drágán számon tartott kincsei ők.' },
  '11-03': { ige: '1Thessz 4,13-14', uzenet: 'Nem úgy gyászolunk, mint akiknek nincs reménységük. A gyászolók mellett szolgálva ezt a különbséget hordozzuk — csendesen, hitelesen.' },
  '11-04': { ige: 'Zsolt 73,25-26', uzenet: 'Ha elfogy is testem és szívem: szívemnek kősziklája és örökségem az Isten mindörökké. Ennél többet a mulandóságról nem lehet mondani.' },
  '11-05': { ige: 'Jel 21,4', uzenet: 'Isten egyszer letöröl minden könnyet, és nem lesz többé sem gyász, sem fájdalom. A vigasztalásunk nem szólam: megígért jövő.' },
  '11-06': { ige: 'Ézs 41,10', uzenet: 'Ne félj, mert én veled vagyok; ne csüggedj, mert én vagyok Istened! Megerősítlek, meg is segítlek — ez az ige ma név szerint nekünk szól.' },
  '11-07': { ige: 'Jn 14,1-3', uzenet: 'Az Atya házában sok hajlék van, és Jézus helyet készít övéinek. A gyászolóknak nem üres szavakat adunk tovább, hanem az ő saját ígéretét.' },
  '11-08': { ige: 'Zsolt 30,6', uzenet: 'Este beszáll hozzánk a sírás, reggelre megjön az öröm. A könnyes időszakok nem örökre szólnak — Isten hajnalt rendelt utánuk.' },
  '11-09': { ige: 'Róm 8,38', uzenet: 'Sem halál, sem élet nem szakíthat el Isten szerelmétől, amely Jézus Krisztusban van. Ez a bizonyosság a hordozó kötelünk — gyászban is.' },
  '11-10': { ige: 'Zsolt 126,5', uzenet: 'Akik könnyhullatással vetnek, vígadozással aratnak majd. A könnyek közt végzett szolgálat nem hiábavaló: aratás készül belőle.' },
  '11-11': { ige: '2Kor 4,17-18', uzenet: 'A pillanatnyi szenvedés örök dicsőséget szerez nekünk. Nem a láthatókra nézünk, hanem a láthatatlanokra — mert azok örökkévalók.' },
  '11-12': { ige: 'Zsolt 147,3', uzenet: 'Meggyógyítja a megtört szívűeket, és bekötözi sebeiket. Isten nem siet el a sebeink mellett — és minket is ilyen figyelemre hív.' },
  '11-13': { ige: 'Mt 5,4', uzenet: 'Boldogok, akik sírnak, mert ők megvigasztaltatnak. Jézus nem azt ígéri, hogy nem lesz sírás — azt ígéri, hogy nem marad vigasz nélkül.' },
  '11-14': { ige: 'Zsolt 145,18', uzenet: 'Közel van az Úr mindenkihez, aki hűséggel hívja őt. Nincs olyan mélység, ahonnan ne hallaná a hozzá kiáltót.' },
  '11-15': { ige: 'Jn 10,27-28', uzenet: 'Jézus név szerint ismeri juhait, és senki ki nem ragadja őket a kezéből. A választói névjegyzék gondozása közben jó tudni: a legfontosabb névsort ő vezeti.' },
  '11-16': { ige: 'Zsolt 100,4', uzenet: 'Menjetek be kapuin hálaadással! A hálaadás idején soroljuk fel bátran: mi mindenért tartozunk köszönettel ebben az évben?' },
  '11-17': { ige: '1Thessz 5,16-18', uzenet: 'Mindenkor örüljetek, szüntelen imádkozzatok, mindenben hálát adjatok. Nem mindenért — mindenben: a nehéz napokban is van miért.' },
  '11-18': { ige: 'Zsolt 136,1', uzenet: 'Magasztaljátok az Urat, mert jó, mert örökkévaló az ő kegyelme! Huszonhatszor ismétli a zsoltár — a hála szeret ismételni.' },
  '11-19': { ige: 'Kol 3,15', uzenet: 'Krisztus békessége uralkodjék a szívünkben — és legyünk háládatosak. A béke és a hála testvérek: együtt szoktak megérkezni.' },
  '11-20': { ige: 'Zsolt 65,12', uzenet: 'Megkoronázod az esztendőt jóvoltoddal — vallja a zsoltár. A lelkészi jelentés készülő sorai mögött is felfedezhetjük: az idei év az ő hűségének lenyomata.' },
  '11-21': { ige: 'Jn 5,24', uzenet: 'Aki hallja Jézus szavát és hisz, már általment a halálból az életre. Az örök élet nem a temetés után kezdődik — már ma a miénk.' },
  '11-22': { ige: 'Zsolt 103,15-17', uzenet: 'Napjaink olyanok, mint a fű — de az Úr kegyelme öröktől fogva mindörökké tart az őt félőkön. A mulandóság közepén ez a mi állandónk.' },
  '11-23': { ige: '2Kor 5,1', uzenet: 'Ha földi sátorházunk elbomlik is, épületünk van Istentől: örökkévaló ház a mennyben. A költözés nem hajléktalanság, hanem hazaérkezés.' },
  '11-24': { ige: 'Zsolt 39,8', uzenet: '„Most azért, mit reméljek, Uram? Tebenned van bizodalmam." Amikor fogynak a válaszok, még mindig marad a legfontosabb: ő maga.' },
  '11-25': { ige: 'Fil 3,20', uzenet: 'A mi országunk a mennyekben van, ahonnan a megtartó Úr Jézust is várjuk. Kettős állampolgárok vagyunk — a végső hűségünk odafenn köt.' },
  '11-26': { ige: 'Zsolt 107,8-9', uzenet: 'Adjanak hálát az Úrnak kegyelméért, mert megelégíti a szomjazó lelket! A hálaadás nem udvariasság — a jóllakott lélek természetes hangja.' },
  '11-27': { ige: '1Pt 1,3-4', uzenet: 'Élő reménységre szült újjá minket Isten — romolhatatlan örökségre. A gyász és a hálaadás hónapjában ez a reménység a tartóoszlopunk.' },
  '11-28': { ige: 'Zsolt 31,16', uzenet: '„Életem ideje kezedben van" — vallotta Dávid. Az évek, a határidők, a fogyó novemberi napok — mind jó kézben vannak.' },
  '11-29': { ige: 'Ézs 25,8', uzenet: 'Az Úr elveszti a halált örökre, és letörli a könnyet minden arcról. A halál nem végállomás, hanem legyőzött ellenség.' },
  '11-30': { ige: 'Róm 15,13', uzenet: 'A reménység Istene töltsön be titeket minden örömmel és békességgel! A hálaadás hónapjából így léphetünk át a várakozás heteibe.' },

  // ── DECEMBER — advent, karácsony, óév ─────────────────────────────────────
  '12-01': { ige: 'Ézs 40,3', uzenet: '„Készítsétek az Úrnak útját!" Advent első napjaiban nem a díszek a legfontosabbak, hanem az útkészítés — a szívünkben.' },
  '12-02': { ige: 'Zsolt 24,7', uzenet: 'Emeljétek fel fejeteket, ti kapuk, hadd menjen be a dicsőség királya! Az adventi kérdés: nyitva áll-e előtte a mi ajtónk is?' },
  '12-03': { ige: 'Zsolt 130,6', uzenet: 'Lelkem várja az Urat, jobban, mint az őrök a reggelt. Az adventi várakozás nem üres idő: a hajnal biztos tudása a sötétben.' },
  '12-04': { ige: 'Mal 3,1', uzenet: '„Eljön templomához az Úr, akit ti kerestek" — üzente a próféta. Az adventi készülődés mögött maga az érkező Isten a válasz.' },
  '12-05': { ige: 'Lk 1,37', uzenet: 'Az Istennél semmi sem lehetetlen — hallotta Mária. Az adventi csodák ma is ott kezdődnek, ahol valaki ezt komolyan meri venni.' },
  '12-06': { ige: 'Ézs 60,1', uzenet: 'Kelj fel, világosodjál, mert eljött világosságod, és az Úr dicsősége rajtad feltámadt! A decemberi sötétben mi hordozhatjuk ezt a fényt.' },
  '12-07': { ige: 'Zsolt 85,11', uzenet: 'Irgalmasság és hűség összetalálkoznak, igazság és békesség csókolgatják egymást. Karácsony felé haladva ez a nagy találkozás készül.' },
  '12-08': { ige: 'Lk 1,46-47', uzenet: '„Magasztalja az én lelkem az Urat" — énekelte Mária. Az adventi teendők között az ő éneke emlékeztet: az öröm is készülődés.' },
  '12-09': { ige: 'Ézs 11,1', uzenet: 'Vesszőszál származik Isai törzsökéből — a levágott fa csonkjából új élet. Isten ott kezd újat, ahol emberileg minden lezárult.' },
  '12-10': { ige: 'Fil 4,4-5', uzenet: 'Örüljetek az Úrban mindenkor — az Úr közel! Az adventi hajszában ez a két szó rendet tesz: közel van, ezért örülhetünk.' },
  '12-11': { ige: 'Mik 5,2', uzenet: 'Betlehem kicsiny volt Júda ezrei között — mégis onnan jött az Uralkodó. Isten a kis helyeket és kis gyülekezeteket sem nézi le.' },
  '12-12': { ige: 'Sof 3,17', uzenet: 'Az Úr közötted van: örül rajtad örömmel, énekléssel örvendez neked. Nemcsak mi készülünk őhozzá — ő is örömmel hajol felénk.' },
  '12-13': { ige: 'Zsolt 40,2', uzenet: 'Várván vártam az Urat, és hozzám hajolt, és meghallgatta kiáltásomat. A hosszú várakozás nem volt hiába — nála sosem az.' },
  '12-14': { ige: 'Jn 1,5', uzenet: 'A világosság a sötétségben fénylik, és a sötétség nem győzte le. A leghosszabb éjszakák idején is ég a fény — és ránk bízatott.' },
  '12-15': { ige: 'Ézs 35,3-4', uzenet: 'Erősítsétek a lankadt kezeket! Mondjátok a remegő szívűeknek: ne féljetek, íme, Istenetek eljön és megszabadít. Ez az adventi szolgálat lényege.' },
  '12-16': { ige: 'Zsid 10,23', uzenet: 'Tartsuk meg reménységünk vallását tántoríthatatlanul, mert hű az, aki ígéretet tett. Nem a mi kitartásunk a horgony — az ő hűsége.' },
  '12-17': { ige: 'Zsolt 96,11-13', uzenet: 'Örüljenek az egek, örvendezzen a föld — mert eljön! Az egész teremtés adventben él: velünk együtt várja az Urat.' },
  '12-18': { ige: 'Ézs 30,15', uzenet: 'A megtérés és a csendesség szabadít meg, a nyugalom és a bizalom erősít meg. Az adventi sok szolgálat között a csend nem lustaság — erőforrás.' },
  '12-19': { ige: 'Lk 1,68', uzenet: 'Áldott az Úr, Izráel Istene, hogy meglátogatta és megváltotta az ő népét! Zakariás hosszú némaság után szólalt meg — hálával.' },
  '12-20': { ige: 'Zsolt 98,1-2', uzenet: 'Énekeljetek az Úrnak új éneket, mert csodadolgokat cselekedett! A karácsonyi énekek nem díszletek: a szabadítás örömhírét hordozzák.' },
  '12-21': { ige: 'Mt 1,21-23', uzenet: 'Nevezd Jézusnak, mert ő szabadítja meg népét bűneiből — és Immánuel lesz: velünk az Isten. A karácsony két neve: Szabadító és Velünk-lévő.' },
  '12-22': { ige: 'Ézs 7,14', uzenet: 'Íme, a szűz fogan méhében, és fiat szül, és nevezi őt Immánuelnek. Évszázados ígéret hajolt be a történelembe — értünk.' },
  '12-23': { ige: 'Ézs 9,6', uzenet: 'Egy gyermek születik nekünk, fiú adatik nekünk: csodálatos tanácsos, erős Isten, békesség fejedelme. Holnap este az ő jászla elé állunk.' },
  '12-24': { ige: 'Lk 2,10-11', uzenet: '„Hirdetek nektek nagy örömet: született néktek ma a Megtartó!" Szentestén minden szolgálatunk ennek az egy mondatnak a visszhangja.' },
  '12-25': { ige: 'Jn 1,14', uzenet: 'Az Ige testté lett, és lakozott miközöttünk — és láttuk az ő dicsőségét. Karácsony titka: Isten nem üzenetet küldött, hanem önmagát adta.' },
  '12-26': { ige: '1Jn 4,9', uzenet: 'Abban nyilvánult meg Isten szeretete, hogy egyszülött Fiát elküldte a világra, hogy éljünk általa. Az ünnep másodnapja is erről az életről szól.' },
  '12-27': { ige: 'Lk 2,19', uzenet: 'Mária megőrizte és szívében forgatta mindezeket. Az ünnepek elmúltával ez a mi dolgunk is: csendben forgatni, amit kaptunk.' },
  '12-28': { ige: 'Zsolt 48,15', uzenet: 'Ez az Isten a mi Istenünk mindörökké: ő vezet minket mindhalálig. Az évek fordulóján sem gazdát váltunk — csak naptárat.' },
  '12-29': { ige: 'JSir 3,40', uzenet: 'Vizsgáljuk meg útjainkat, és térjünk vissza az Úrhoz! Az év végi számvetés — a zárások és kimutatások között — először mindig a szívben kezdődik.' },
  '12-30': { ige: '1Sám 7,12', uzenet: '„Mindeddig megsegített minket az Úr!" Sámuel emlékkövet állított — az évzáró leltár és a számadás sorai közé mi is odaírhatjuk ezt a mondatot.' },
  '12-31': { ige: 'Zsolt 90,12', uzenet: 'Taníts minket úgy számlálni napjainkat, hogy bölcs szívhez jussunk! Az óév estéjén hálával tesszük le az esztendőt — kezéből vettük minden napját.' },
}
