-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public._merge_run_log (
  id integer NOT NULL DEFAULT nextval('_merge_run_log_id_seq'::regclass),
  phase text,
  ferj_csalad_id integer,
  no_csalad_id integer,
  action text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT _merge_run_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public._merge_v7_result (
  phase text,
  merged integer,
  skipped integer,
  first_error text,
  ran_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.access_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  full_name text NOT NULL,
  requested_role text NOT NULL CHECK (requested_role = ANY (ARRAY['lelkesz'::text, 'esperes'::text, 'egyhazmegyei_admin'::text, 'egyhazkeruleti_admin'::text, 'konyvelo'::text, 'egyhazmegyei_szamvevo'::text])),
  congregation_slug text,
  phone text,
  justification text,
  referrer text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  admin_notes text,
  ip_hash text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  resulting_user_id uuid,
  CONSTRAINT access_requests_pkey PRIMARY KEY (id),
  CONSTRAINT access_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT access_requests_resulting_user_id_fkey FOREIGN KEY (resulting_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_access_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_user_id uuid NOT NULL,
  congregation_id uuid NOT NULL,
  pastor_user_id uuid,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'expired'::text])),
  approved_at timestamp with time zone,
  denied_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_access_requests_pkey PRIMARY KEY (id),
  CONSTRAINT admin_access_requests_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES auth.users(id),
  CONSTRAINT admin_access_requests_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT admin_access_requests_pastor_user_id_fkey FOREIGN KEY (pastor_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.adrcountry (
  id integer NOT NULL DEFAULT nextval('adrcountry_id_seq'::regclass),
  name character varying NOT NULL,
  sname character varying,
  usagecnt integer,
  name_hu text,
  name_ro text,
  CONSTRAINT adrcountry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.adrcounty (
  id integer NOT NULL DEFAULT nextval('adrcounty_id_seq'::regclass),
  name character varying NOT NULL,
  sname character varying,
  countryid integer NOT NULL,
  usagecnt integer,
  name_hu text,
  name_ro text,
  auto_code text,
  siruta_code text,
  CONSTRAINT adrcounty_pkey PRIMARY KEY (id),
  CONSTRAINT adrcounty_countryid_fk FOREIGN KEY (countryid) REFERENCES public.adrcountry(id)
);
CREATE TABLE public.adrlocality (
  id integer NOT NULL DEFAULT nextval('adrlocality_id_seq'::regclass),
  name character varying NOT NULL,
  code character varying,
  countyid integer NOT NULL,
  usagecnt integer,
  name_hu text,
  name_ro text,
  siruta_code text,
  geonames_id integer,
  default_postalcode text,
  feature_code text,
  needs_review boolean NOT NULL DEFAULT false,
  review_source text,
  CONSTRAINT adrlocality_pkey PRIMARY KEY (id),
  CONSTRAINT adrlocality_countyid_fk FOREIGN KEY (countyid) REFERENCES public.adrcounty(id)
);
CREATE TABLE public.adrlocality_alias (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  adrlocality_id integer NOT NULL,
  alias_name text NOT NULL,
  lang text,
  source text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT adrlocality_alias_pkey PRIMARY KEY (id),
  CONSTRAINT adrlocality_alias_locality_fk FOREIGN KEY (adrlocality_id) REFERENCES public.adrlocality(id)
);
CREATE TABLE public.adrstreet (
  id integer NOT NULL DEFAULT nextval('adrstreet_id_seq'::regclass),
  name character varying NOT NULL,
  postalcode character varying,
  localityid integer NOT NULL,
  usagecnt integer,
  name_hu text,
  name_ro text,
  street_type_hu text,
  street_type_ro text,
  CONSTRAINT adrstreet_pkey PRIMARY KEY (id),
  CONSTRAINT adrstreet_localityid_fk FOREIGN KEY (localityid) REFERENCES public.adrlocality(id)
);
CREATE TABLE public.annual_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid,
  year integer NOT NULL,
  members_count integer DEFAULT 0,
  services_count integer DEFAULT 0,
  total_income numeric DEFAULT 0,
  pastor_note text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'received'::text, 'reviewed'::text, 'finalized'::text])),
  submitted_at timestamp with time zone DEFAULT now(),
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  submitted_by uuid,
  received_at timestamp with time zone,
  received_by uuid,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_notes text,
  finalized_at timestamp with time zone,
  finalized_by uuid,
  forwarded_to_kerulet boolean NOT NULL DEFAULT false,
  forwarded_at timestamp with time zone,
  deleted boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT annual_reports_pkey PRIMARY KEY (id),
  CONSTRAINT annual_reports_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT annual_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT annual_reports_received_by_fkey FOREIGN KEY (received_by) REFERENCES auth.users(id),
  CONSTRAINT annual_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT annual_reports_finalized_by_fkey FOREIGN KEY (finalized_by) REFERENCES auth.users(id)
);
CREATE TABLE public.attert (
  id integer NOT NULL DEFAULT nextval('attert_id_seq'::regclass),
  id_szemely integer NOT NULL,
  felekezet character varying,
  mikor timestamp without time zone,
  igazolas character varying,
  megjegyzes character varying,
  honnanid integer,
  congregation_id uuid,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attert_pkey PRIMARY KEY (id),
  CONSTRAINT attert_honnanid_fk FOREIGN KEY (honnanid) REFERENCES public.adrlocality(id),
  CONSTRAINT attert_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT attert_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  device_id uuid,
  action text NOT NULL,
  target_table text,
  target_id uuid,
  metadata jsonb,
  ip inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT audit_log_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.user_devices(id)
);
CREATE TABLE public.bankszamla_nyito_egyenleg (
  id bigint NOT NULL DEFAULT nextval('bankszamla_nyito_egyenleg_id_seq'::regclass),
  bankszamla_id integer NOT NULL,
  congregation_id uuid NOT NULL,
  eve integer NOT NULL CHECK (eve >= 2000 AND eve <= 2100),
  nyito_egyenleg_valuta numeric NOT NULL DEFAULT 0,
  nyito_egyenleg_ron numeric NOT NULL DEFAULT 0,
  arfolyam numeric,
  forrasa text NOT NULL DEFAULT 'manual'::text CHECK (forrasa = ANY (ARRAY['manual'::text, 'import'::text, 'carryover'::text])),
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT bankszamla_nyito_egyenleg_pkey PRIMARY KEY (id),
  CONSTRAINT bankszamla_nyito_egyenleg_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id),
  CONSTRAINT bankszamla_nyito_egyenleg_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT bankszamla_nyito_egyenleg_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT bankszamla_nyito_egyenleg_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bankszamlak (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  congregation_id uuid,
  bank_neve character varying NOT NULL,
  iban character varying,
  valuta character varying DEFAULT 'RON'::character varying,
  aktiv boolean DEFAULT true,
  nyito_egyenleg numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  szin character varying DEFAULT '#206bc4'::character varying,
  is_default boolean DEFAULT false,
  ikon text DEFAULT 'building-2'::text,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  scope text NOT NULL DEFAULT 'gyulekezet'::text CHECK (scope = ANY (ARRAY['gyulekezet'::text, 'egyhazmegye'::text])),
  diocese_id uuid,
  CONSTRAINT bankszamlak_pkey PRIMARY KEY (id),
  CONSTRAINT bankszamlak_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT bankszamlak_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id)
);
CREATE TABLE public.bealitas (
  id character varying NOT NULL,
  intezmenyneve character varying,
  utcaid integer NOT NULL,
  szam character varying,
  telefon character varying,
  lelkesz character varying,
  logo character varying,
  isszemelyibefizetes boolean NOT NULL,
  isszulokkulon boolean NOT NULL,
  szemelyibefizetesfilter character varying,
  felmentes70felul boolean NOT NULL,
  felmenteskorhatar character varying,
  felmentesideneskudtek boolean NOT NULL,
  kedvezmenyxevenfelul boolean NOT NULL,
  kedvezmenykorhatar integer,
  kedvezmeny integer,
  egyhazkerulet character varying,
  egyhazmegye character varying,
  adoazonosito character varying,
  bejegyzesiszam character varying,
  aktiv boolean NOT NULL,
  ervenyessegiev timestamp without time zone,
  version character varying,
  created timestamp without time zone,
  congregation_id uuid NOT NULL,
  intezmenyneve_ro character varying,
  helysegid integer,
  diak_felmentes boolean DEFAULT false,
  eves_jarulek numeric DEFAULT 0,
  budget_finalized boolean DEFAULT false,
  presbiteriumi_hatarozat_datum date,
  presbiteriumi_hatarozat_szam character varying,
  egyhazkozsegi_iktatoszam character varying,
  egyhazmegyei_iktatoszam character varying,
  unlock_requested boolean DEFAULT false,
  unlock_reason text,
  szamadas_zaro_adatok jsonb DEFAULT '{}'::jsonb,
  accounting_finalized boolean DEFAULT false,
  accounting_unlock_requested boolean DEFAULT false,
  accounting_unlock_reason text,
  leltar_finalized boolean DEFAULT false,
  leltar_unlock_requested boolean DEFAULT false,
  leltar_unlock_reason text,
  nyito_keszpenz numeric DEFAULT 0,
  nyito_bank numeric DEFAULT 0,
  jarulek_kedvezmenyes numeric DEFAULT 0,
  jarulek_hatarid text DEFAULT '07-01'::text,
  szamadas_iktatoszam character varying,
  szamadas_hatarozat_datum date,
  szamadas_hatarozat_szam character varying,
  leltar_iktatoszam character varying,
  leltar_hatarozat_datum date,
  leltar_hatarozat_szam character varying,
  CONSTRAINT bealitas_pkey PRIMARY KEY (id, congregation_id),
  CONSTRAINT bealitas_utcaid_fk FOREIGN KEY (utcaid) REFERENCES public.adrstreet(id),
  CONSTRAINT bealitas_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT bealitas_helysegid_fkey FOREIGN KEY (helysegid) REFERENCES public.adrlocality(id)
);
CREATE TABLE public.befizetes (
  id integer NOT NULL DEFAULT nextval('befizetes_id_seq'::regclass),
  xkey character varying NOT NULL,
  id_csalad integer,
  id_szemely integer,
  forrasa text NOT NULL,
  id_befizetescel integer NOT NULL,
  datum date NOT NULL,
  osszeg numeric NOT NULL,
  nyugta text NOT NULL,
  iratszam text NOT NULL,
  irattipus text NOT NULL,
  csalad boolean NOT NULL,
  megjegyzes text,
  deleted boolean NOT NULL,
  created timestamp without time zone,
  fizetettev integer NOT NULL,
  userid uuid NOT NULL,
  melleklet integer,
  synced boolean DEFAULT false,
  congregation_id uuid,
  is_potlas boolean DEFAULT false,
  bankszamla_id integer,
  belso_mozgas_xkey character varying,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stornozott boolean NOT NULL DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_indok text,
  stornozott_by uuid,
  osszeg_ron numeric,
  arfolyam numeric,
  CONSTRAINT befizetes_pkey PRIMARY KEY (id),
  CONSTRAINT befizetes_id_befizetescel_fk FOREIGN KEY (id_befizetescel) REFERENCES public.befizetescel(id),
  CONSTRAINT befizetes_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id),
  CONSTRAINT befizetes_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT befizetes_userid_fk FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT befizetes_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT befizetes_stornozott_by_fkey FOREIGN KEY (stornozott_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.befizetescel (
  id integer NOT NULL DEFAULT nextval('befizetescel_id_seq'::regclass),
  nevro character varying NOT NULL,
  nev character varying NOT NULL,
  id_szamadasicel character varying NOT NULL UNIQUE,
  aktiv boolean NOT NULL,
  belsotetel character varying,
  parentid integer,
  CONSTRAINT befizetescel_pkey PRIMARY KEY (id),
  CONSTRAINT befizetescel_parentid_fk FOREIGN KEY (parentid) REFERENCES public.befizetescel(id),
  CONSTRAINT befizetescel_id_szamadasicel_fk FOREIGN KEY (id_szamadasicel) REFERENCES public.szamadasicel(id)
);
CREATE TABLE public.bekoltozott (
  id integer NOT NULL DEFAULT nextval('bekoltozott_id_seq'::regclass),
  id_szemely integer NOT NULL,
  mikor timestamp without time zone NOT NULL,
  megjegyzes character varying,
  igazolas character varying,
  honnanid integer,
  congregation_id uuid,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bekoltozott_pkey PRIMARY KEY (id),
  CONSTRAINT bekoltozott_honnanid_fk FOREIGN KEY (honnanid) REFERENCES public.adrlocality(id),
  CONSTRAINT bekoltozott_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT bekoltozott_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.belsomozgas (
  id bigint NOT NULL DEFAULT nextval('belsomozgas_id_seq'::regclass),
  congregation_id uuid NOT NULL,
  datum date NOT NULL DEFAULT CURRENT_DATE,
  tipus text NOT NULL CHECK (tipus = ANY (ARRAY['kassza_bank'::text, 'bank_kassza'::text, 'bank_bank'::text, 'valutacsere'::text])),
  forras text NOT NULL,
  cel text NOT NULL,
  osszeg numeric NOT NULL,
  cel_osszeg numeric,
  arfolyam numeric,
  megjegyzes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  deleted boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT belsomozgas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.berleti_szerzodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  berlo_nev text NOT NULL,
  id_szemely integer,
  targy text,
  leiras text NOT NULL,
  tipus text DEFAULT 'terulet'::text CHECK (tipus = ANY (ARRAY['terulet'::text, 'epulet'::text])),
  osszeg numeric NOT NULL,
  fizetesi_ciklus text DEFAULT 'eves'::text CHECK (fizetesi_ciklus = ANY (ARRAY['havi'::text, 'eves'::text])),
  kezdet date NOT NULL,
  vege date,
  id_szamadasicel text DEFAULT '104.05'::text,
  leltari_szam text,
  telekkonyvi_szam text,
  ceg_nev text,
  ceg_adoszam text,
  aktiv boolean DEFAULT true,
  megjegyzes text,
  created_at timestamp with time zone DEFAULT now(),
  userid uuid,
  deleted boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  jogi_tipus text NOT NULL DEFAULT 'locatiune'::text CHECK (jogi_tipus = ANY (ARRAY['locatiune'::text, 'arendare'::text, 'comodat'::text, 'concesiune'::text])),
  oblio_auto_szamlaz boolean NOT NULL DEFAULT false,
  oblio_klienesseg_id text,
  oblio_termek_kod text,
  CONSTRAINT berleti_szerzodes_pkey PRIMARY KEY (id),
  CONSTRAINT berleti_szerzodes_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT berleti_szerzodes_id_szemely_fkey FOREIGN KEY (id_szemely) REFERENCES public.szemely(id)
);
CREATE TABLE public.chitanta_tombok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid,
  block_nr text,
  seria text NOT NULL,
  szam_kezdet integer NOT NULL,
  szam_veg integer NOT NULL,
  darabszam_ossz integer NOT NULL CHECK (darabszam_ossz > 0),
  felhasznalt_darabszam integer NOT NULL DEFAULT 0,
  vasarlas_datuma date NOT NULL DEFAULT CURRENT_DATE,
  vasarlas_ara numeric,
  elso_hasznalat_datum date,
  utolso_hasznalat_datum date,
  aktiv boolean NOT NULL DEFAULT true,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  scope text NOT NULL DEFAULT 'gyulekezet'::text CHECK (scope = ANY (ARRAY['gyulekezet'::text, 'egyhazmegye'::text])),
  diocese_id uuid,
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT chitanta_tombok_pkey PRIMARY KEY (id),
  CONSTRAINT chitanta_tombok_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT chitanta_tombok_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id)
);
CREATE TABLE public.congregation_annual_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  year integer NOT NULL,
  eves_jarulek numeric NOT NULL DEFAULT 0,
  jarulek_kedvezmenyes numeric DEFAULT 0,
  jarulek_hatarid character varying DEFAULT '07-01'::character varying,
  note text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT congregation_annual_fees_pkey PRIMARY KEY (id),
  CONSTRAINT congregation_annual_fees_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.congregation_custom_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency text NOT NULL DEFAULT 'RON'::text,
  year_from integer NOT NULL,
  year_to integer,
  kor_tol integer,
  kor_ig integer,
  aktiv boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT congregation_custom_fees_pkey PRIMARY KEY (id),
  CONSTRAINT congregation_custom_fees_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT congregation_custom_fees_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.congregation_subscriptions (
  id bigint NOT NULL DEFAULT nextval('congregation_subscriptions_id_seq'::regclass),
  congregation_id uuid NOT NULL,
  pricing_tier_id bigint,
  tipus text NOT NULL DEFAULT 'havi'::text CHECK (tipus = ANY (ARRAY['havi'::text, 'eves'::text, 'teszt'::text, 'kedvezmeny'::text, 'ingyenes'::text])),
  dij_ron numeric,
  kezdet date NOT NULL DEFAULT CURRENT_DATE,
  veg date,
  aktiv boolean NOT NULL DEFAULT true,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT congregation_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT congregation_subscriptions_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT congregation_subscriptions_pricing_tier_id_fkey FOREIGN KEY (pricing_tier_id) REFERENCES public.system_pricing_tiers(id)
);
CREATE TABLE public.congregations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  diocese text,
  district text DEFAULT 'Erdélyi Református Egyházkerület'::text,
  created_at timestamp with time zone DEFAULT now(),
  nev_hu character varying,
  nev_ro character varying,
  nev_en character varying,
  egyhazmegye character varying,
  adoszam character varying,
  cim character varying,
  email character varying,
  telefon character varying,
  web character varying,
  eves_jarulek numeric DEFAULT 100,
  iban character varying,
  bank character varying,
  cimer_url character varying,
  diocese_id uuid,
  jarulek_kedvezmenyes numeric DEFAULT 0,
  jarulek_hatarid text DEFAULT '07-01'::text,
  public_slug text,
  public_site_enabled boolean NOT NULL DEFAULT false,
  tva_alany boolean NOT NULL DEFAULT false,
  tva_alany_tol date,
  tva_kod text,
  e_factura_kotelezett boolean NOT NULL DEFAULT false,
  e_factura_kotelezett_tol date,
  e_factura_kotelezettseg_indoka text,
  varos text,
  megye text,
  adrlocality_id integer,
  adrstreet_id integer,
  iranyitoszam text,
  hazszam text,
  country text DEFAULT 'Románia'::text,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT congregations_pkey PRIMARY KEY (id),
  CONSTRAINT congregations_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id),
  CONSTRAINT congregations_adrlocality_fk FOREIGN KEY (adrlocality_id) REFERENCES public.adrlocality(id),
  CONSTRAINT congregations_adrstreet_fk FOREIGN KEY (adrstreet_id) REFERENCES public.adrstreet(id)
);
CREATE TABLE public.cross_congregation_match_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['new_member'::text, 'update_match'::text])),
  triggering_szemely_id integer NOT NULL,
  triggering_congregation_id uuid NOT NULL,
  matched_szemely_id integer NOT NULL,
  matched_congregation_id uuid NOT NULL,
  confidence text NOT NULL CHECK (confidence = ANY (ARRAY['name_phone'::text, 'name_birth'::text, 'phone_only'::text, 'name_only'::text])),
  resolution text CHECK (resolution = ANY (ARRAY['same_person'::text, 'different_person'::text, 'dismissed'::text])),
  resolved_by_triggering_user uuid,
  resolved_by_matched_user uuid,
  resolved_at timestamp with time zone,
  seen_by_triggering_user_at timestamp with time zone,
  seen_by_matched_user_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cross_congregation_match_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT cross_congregation_match_notificatio_triggering_szemely_id_fkey FOREIGN KEY (triggering_szemely_id) REFERENCES public.szemely(id),
  CONSTRAINT cross_congregation_match_notifi_triggering_congregation_id_fkey FOREIGN KEY (triggering_congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT cross_congregation_match_notifications_matched_szemely_id_fkey FOREIGN KEY (matched_szemely_id) REFERENCES public.szemely(id),
  CONSTRAINT cross_congregation_match_notificat_matched_congregation_id_fkey FOREIGN KEY (matched_congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT cross_congregation_match_notif_resolved_by_triggering_user_fkey FOREIGN KEY (resolved_by_triggering_user) REFERENCES auth.users(id),
  CONSTRAINT cross_congregation_match_notifica_resolved_by_matched_user_fkey FOREIGN KEY (resolved_by_matched_user) REFERENCES auth.users(id)
);
CREATE TABLE public.csalad (
  id integer NOT NULL DEFAULT nextval('csalad_id_seq'::regclass),
  id_ferfi integer,
  id_no integer,
  c_utcaid integer NOT NULL,
  c_szam character varying NOT NULL,
  c_tombhaz character varying,
  c_lepcsohaz character varying,
  c_ajto character varying,
  c_emelet character varying,
  id_csoport integer,
  isaktiv boolean NOT NULL,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT csalad_pkey PRIMARY KEY (id),
  CONSTRAINT csalad_c_utcaid_fk FOREIGN KEY (c_utcaid) REFERENCES public.adrstreet(id),
  CONSTRAINT csalad_id_csoport_fk FOREIGN KEY (id_csoport) REFERENCES public.csoport(id),
  CONSTRAINT csalad_id_ferfi_fk FOREIGN KEY (id_ferfi) REFERENCES public.szemely(id),
  CONSTRAINT csalad_id_no_fk FOREIGN KEY (id_no) REFERENCES public.szemely(id)
);
CREATE TABLE public.csaladlatogatas (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  id_csalad integer NOT NULL,
  datum date NOT NULL,
  lelkesz character varying NOT NULL,
  alapige character varying,
  megjegyzes text,
  munkanaplo_id integer,
  congregation_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT csaladlatogatas_pkey PRIMARY KEY (id),
  CONSTRAINT csaladlatogatas_id_csalad_fkey FOREIGN KEY (id_csalad) REFERENCES public.csalad(id),
  CONSTRAINT csaladlatogatas_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.csoport (
  id integer NOT NULL DEFAULT nextval('csoport_id_seq'::regclass),
  nev character varying NOT NULL,
  kep character varying,
  isaktiv boolean NOT NULL,
  iskorzet boolean NOT NULL,
  created timestamp without time zone,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT csoport_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_wipe_log (
  id bigint NOT NULL DEFAULT nextval('data_wipe_log_id_seq'::regclass),
  congregation_id uuid NOT NULL,
  congregation_name text NOT NULL,
  initiated_by uuid NOT NULL,
  initiated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_tables jsonb NOT NULL,
  total_rows_deleted bigint NOT NULL DEFAULT 0,
  CONSTRAINT data_wipe_log_pkey PRIMARY KEY (id),
  CONSTRAINT data_wipe_log_congregation_fk FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.diocese_annual_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  diocese_id uuid NOT NULL,
  year integer NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'received'::text, 'reviewed'::text, 'finalized'::text])),
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  submitted_at timestamp with time zone,
  submitted_by uuid,
  received_at timestamp with time zone,
  received_by uuid,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_notes text,
  finalized_at timestamp with time zone,
  finalized_by uuid,
  forwarded_to_kerulet boolean NOT NULL DEFAULT false,
  forwarded_at timestamp with time zone,
  deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diocese_annual_reports_pkey PRIMARY KEY (id),
  CONSTRAINT diocese_annual_reports_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id)
);
CREATE TABLE public.diocese_bealitas (
  id bigint NOT NULL DEFAULT nextval('diocese_bealitas_id_seq'::regclass),
  diocese_id uuid NOT NULL,
  eve integer NOT NULL,
  koltsegvetes_veglegesitve boolean NOT NULL DEFAULT false,
  koltsegvetes_veglegesites_datuma date,
  koltsegvetes_veglegesitette uuid,
  szamadas_veglegesitve boolean NOT NULL DEFAULT false,
  szamadas_veglegesites_datuma date,
  szamadas_veglegesitette uuid,
  szamadas_unlock_requested boolean NOT NULL DEFAULT false,
  szamadas_unlock_request_reason text,
  szamadas_unlock_request_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diocese_bealitas_pkey PRIMARY KEY (id),
  CONSTRAINT diocese_bealitas_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id)
);
CREATE TABLE public.diocese_befizetes (
  id bigint NOT NULL DEFAULT nextval('diocese_befizetes_id_seq'::regclass),
  diocese_id uuid NOT NULL,
  datum date NOT NULL,
  osszeg numeric NOT NULL,
  osszeg_ron numeric,
  arfolyam numeric,
  id_szamadasicel text NOT NULL,
  forrasa text NOT NULL,
  befizeto_congregation_id uuid,
  iratszam text NOT NULL,
  nyugta text NOT NULL,
  irattipus text NOT NULL DEFAULT 'készpénz'::text CHECK (irattipus = ANY (ARRAY['készpénz'::text, 'banki'::text, 'számla'::text])),
  bankszamla_id integer,
  megjegyzes text,
  fizetettev integer,
  xkey text NOT NULL,
  userid uuid,
  deleted boolean NOT NULL DEFAULT false,
  stornozott boolean NOT NULL DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_by uuid,
  stornozott_indok text,
  source_befizetes_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diocese_befizetes_pkey PRIMARY KEY (id),
  CONSTRAINT diocese_befizetes_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id),
  CONSTRAINT diocese_befizetes_id_szamadasicel_fkey FOREIGN KEY (id_szamadasicel) REFERENCES public.szamadasicel(id),
  CONSTRAINT diocese_befizetes_befizeto_congregation_id_fkey FOREIGN KEY (befizeto_congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT diocese_befizetes_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id),
  CONSTRAINT diocese_befizetes_source_befizetes_id_fkey FOREIGN KEY (source_befizetes_id) REFERENCES public.befizetes(id)
);
CREATE TABLE public.diocese_kiadas (
  id bigint NOT NULL DEFAULT nextval('diocese_kiadas_id_seq'::regclass),
  diocese_id uuid NOT NULL,
  datum date NOT NULL,
  osszeg numeric NOT NULL,
  osszeg_ron numeric,
  arfolyam numeric,
  id_szamadasicel text NOT NULL,
  kedvezmenyezett text NOT NULL,
  kedvezmenyezett_cui text,
  kedvezmenyezett_congregation_id uuid,
  iratszam text NOT NULL,
  nyugta text NOT NULL,
  irattipus text NOT NULL DEFAULT 'készpénz'::text CHECK (irattipus = ANY (ARRAY['készpénz'::text, 'banki'::text, 'számla'::text])),
  bankszamla_id integer,
  megjegyzes text,
  xkey text NOT NULL,
  userid uuid,
  deleted boolean NOT NULL DEFAULT false,
  stornozott boolean NOT NULL DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_by uuid,
  stornozott_indok text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diocese_kiadas_pkey PRIMARY KEY (id),
  CONSTRAINT diocese_kiadas_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id),
  CONSTRAINT diocese_kiadas_id_szamadasicel_fkey FOREIGN KEY (id_szamadasicel) REFERENCES public.szamadasicel(id),
  CONSTRAINT diocese_kiadas_kedvezmenyezett_congregation_id_fkey FOREIGN KEY (kedvezmenyezett_congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT diocese_kiadas_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id)
);
CREATE TABLE public.diocese_koltsegvetes (
  diocese_id uuid NOT NULL,
  eve integer NOT NULL,
  szamadasicelid text NOT NULL,
  tervezett numeric NOT NULL DEFAULT 0,
  osszeg_mod_1 numeric DEFAULT 0,
  osszeg_mod_2 numeric DEFAULT 0,
  osszeg_mod_3 numeric DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diocese_koltsegvetes_pkey PRIMARY KEY (diocese_id, eve, szamadasicelid),
  CONSTRAINT diocese_koltsegvetes_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id),
  CONSTRAINT diocese_koltsegvetes_szamadasicelid_fkey FOREIGN KEY (szamadasicelid) REFERENCES public.szamadasicel(id)
);
CREATE TABLE public.dioceses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  district_id uuid,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  cif text,
  adoszam text,
  cnp_letter text,
  cim_orszag text DEFAULT 'Románia'::text,
  cim_megye text,
  cim_telepules text,
  cim_iranyitoszam text,
  cim_utca text,
  email text,
  telefon text,
  weboldal text,
  bank_nev text,
  bank_fo_iban text,
  bank_fo_iban_valuta text DEFAULT 'RON'::text,
  esperes_nev text,
  esperes_cim text,
  jegyzo_nev text,
  megjegyzes text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  adrlocality_id integer,
  adrstreet_id integer,
  CONSTRAINT dioceses_pkey PRIMARY KEY (id),
  CONSTRAINT dioceses_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT dioceses_adrlocality_fk FOREIGN KEY (adrlocality_id) REFERENCES public.adrlocality(id),
  CONSTRAINT dioceses_adrstreet_fk FOREIGN KEY (adrstreet_id) REFERENCES public.adrstreet(id)
);
CREATE TABLE public.districts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT districts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  device_id uuid NOT NULL,
  wrapped_dek bytea NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_keys_pkey PRIMARY KEY (id),
  CONSTRAINT document_keys_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_keys_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.user_devices(id)
);
CREATE TABLE public.document_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  diocese_id uuid,
  year integer NOT NULL,
  document_type text NOT NULL,
  modification_number integer,
  status text NOT NULL DEFAULT 'submitted'::text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  received_at timestamp with time zone,
  received_by uuid,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  finalized_at timestamp with time zone,
  finalized_by uuid,
  forwarded_to_kerulet boolean NOT NULL DEFAULT false,
  forwarded_at timestamp with time zone,
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  CONSTRAINT document_submissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  congregation_id uuid,
  storage_path text NOT NULL UNIQUE,
  filename_encrypted bytea NOT NULL,
  mime_type text,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT documents_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT documents_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.elkoltozott (
  id integer NOT NULL DEFAULT nextval('elkoltozott_id_seq'::regclass),
  id_szemely integer NOT NULL,
  kulfoldre boolean NOT NULL,
  mikor timestamp without time zone,
  megjegyzes character varying,
  hovaid integer,
  congregation_id uuid,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT elkoltozott_pkey PRIMARY KEY (id),
  CONSTRAINT elkoltozott_hovaid_fk FOREIGN KEY (hovaid) REFERENCES public.adrlocality(id),
  CONSTRAINT elkoltozott_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT elkoltozott_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.ertesitesek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid,
  cim character varying NOT NULL,
  uzenet text,
  tipus character varying DEFAULT 'info'::character varying,
  olvasva boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  hivatkozas text,
  admin_request_id uuid,
  CONSTRAINT ertesitesek_pkey PRIMARY KEY (id),
  CONSTRAINT ertesitesek_admin_request_id_fkey FOREIGN KEY (admin_request_id) REFERENCES public.admin_access_requests(id),
  CONSTRAINT ertesitesek_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.event (
  type character varying NOT NULL,
  val character varying NOT NULL,
  created timestamp without time zone NOT NULL
);
CREATE TABLE public.family_link_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL,
  congregation_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['spouse_link'::text, 'child_link'::text, 'family_create'::text])),
  csalad_id integer,
  szemely_id integer,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence text NOT NULL CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  reverted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT family_link_audit_pkey PRIMARY KEY (id),
  CONSTRAINT family_link_audit_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT family_link_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT family_link_audit_csalad_id_fkey FOREIGN KEY (csalad_id) REFERENCES public.csalad(id),
  CONSTRAINT family_link_audit_szemely_id_fkey FOREIGN KEY (szemely_id) REFERENCES public.szemely(id)
);
CREATE TABLE public.felmentes (
  id integer NOT NULL DEFAULT nextval('felmentes_id_seq'::regclass),
  id_csalad integer,
  felmento character varying NOT NULL,
  datum timestamp without time zone NOT NULL,
  oka character varying NOT NULL,
  kezdete integer,
  vege integer,
  created timestamp without time zone,
  id_szemely integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT felmentes_pkey PRIMARY KEY (id),
  CONSTRAINT felmentes_id_csalad_fk FOREIGN KEY (id_csalad) REFERENCES public.csalad(id),
  CONSTRAINT felmentes_id_szemely_fkey FOREIGN KEY (id_szemely) REFERENCES public.szemely(id)
);
CREATE TABLE public.gyerek (
  id integer NOT NULL DEFAULT nextval('gyerek_id_seq'::regclass),
  id_csalad integer NOT NULL,
  id_szemely integer NOT NULL,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gyerek_pkey PRIMARY KEY (id),
  CONSTRAINT gyerek_id_csalad_fk FOREIGN KEY (id_csalad) REFERENCES public.csalad(id),
  CONSTRAINT gyerek_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id)
);
CREATE TABLE public.gyulekezeti_programok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  cim text NOT NULL,
  leiras text,
  datum date NOT NULL,
  ido_kezdes time without time zone,
  ido_befejezes time without time zone,
  helyszin text,
  tipus text DEFAULT 'istentisztelet'::text CHECK (tipus = ANY (ARRAY['istentisztelet'::text, 'bibliaora'::text, 'imaora'::text, 'ifjusagi'::text, 'gyerekprogram'::text, 'konferencia'::text, 'hangverseny'::text, 'kozossegi'::text, 'presbiteri'::text, 'latogatas'::text, 'unnep'::text, 'tabor'::text, 'evangelizacio'::text, 'diakoniai'::text, 'noszovetseg'::text, 'egyeb'::text])),
  szin text DEFAULT '#206bc4'::text,
  ismétlődő boolean DEFAULT false,
  ismetlodes_tipus text CHECK (ismetlodes_tipus = ANY (ARRAY['heti'::text, 'ketheti'::text, 'havi'::text, NULL::text])),
  prioritas text DEFAULT 'normal'::text CHECK (prioritas = ANY (ARRAY['alacsony'::text, 'normal'::text, 'fontos'::text, 'kiemelt'::text])),
  teljesitett boolean DEFAULT false,
  teljesites_datum timestamp with time zone,
  megjegyzes text,
  letrehozta_id uuid NOT NULL,
  letrehozta_nev text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  datum_vege date,
  egyedi_tipus_nev text,
  egyedi_emoji text,
  CONSTRAINT gyulekezeti_programok_pkey PRIMARY KEY (id),
  CONSTRAINT gyulekezeti_programok_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT gyulekezeti_programok_letrehozta_id_fkey FOREIGN KEY (letrehozta_id) REFERENCES auth.users(id)
);
CREATE TABLE public.hazassag (
  id integer NOT NULL DEFAULT nextval('hazassag_id_seq'::regclass),
  id_ferfi integer NOT NULL,
  id_no integer NOT NULL,
  datum timestamp without time zone NOT NULL,
  lelkeszneve character varying,
  hlevel character varying,
  tanuk character varying,
  megjegyzes character varying,
  munkanaploba boolean NOT NULL,
  helyid integer,
  congregation_id uuid,
  munkanaplo_id integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hazassag_pkey PRIMARY KEY (id),
  CONSTRAINT hazassag_helyid_fk FOREIGN KEY (helyid) REFERENCES public.adrlocality(id),
  CONSTRAINT hazassag_id_ferfi_fk FOREIGN KEY (id_ferfi) REFERENCES public.szemely(id),
  CONSTRAINT hazassag_id_no_fk FOREIGN KEY (id_no) REFERENCES public.szemely(id),
  CONSTRAINT hazassag_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.iktato (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  year integer NOT NULL,
  sequence_number integer NOT NULL DEFAULT nextval('iktato_sequence_number_seq'::regclass),
  direction text CHECK (direction = ANY (ARRAY['incoming'::text, 'outgoing'::text])),
  subject text NOT NULL,
  sender_or_recipient text,
  file_folder text,
  created_at timestamp with time zone DEFAULT now(),
  kelt date,
  targykivonat text,
  elintezes_ideje date,
  elintezes_modja text,
  irattarijel text,
  oldalszam integer,
  megjegyzes text,
  deleted boolean DEFAULT false,
  userid uuid,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iktato_pkey PRIMARY KEY (id),
  CONSTRAINT iktato_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.iktato_sablonok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  nev text NOT NULL,
  tipus text NOT NULL DEFAULT 'egyeb'::text CHECK (tipus = ANY (ARRAY['igazolas'::text, 'level'::text, 'hatarozat'::text, 'meghivo'::text, 'jegyzokonyv'::text, 'egyeb'::text])),
  leiras text,
  tartalom text NOT NULL,
  aktiv boolean DEFAULT true,
  sorrend integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT iktato_sablonok_pkey PRIMARY KEY (id),
  CONSTRAINT iktato_sablonok_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT iktato_sablonok_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.import_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  module text NOT NULL CHECK (module = ANY (ARRAY['members'::text, 'finance'::text, 'registry'::text, 'worklog'::text, 'filing'::text, 'inventory'::text])),
  file_name text NOT NULL,
  total_inserted integer NOT NULL DEFAULT 0,
  total_skipped integer NOT NULL DEFAULT 0,
  per_sheet jsonb DEFAULT '[]'::jsonb,
  lookup_stats jsonb DEFAULT '{}'::jsonb,
  errors jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT import_logs_pkey PRIMARY KEY (id),
  CONSTRAINT import_logs_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT import_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.iratszam_pointers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  iratszam_tipus text NOT NULL CHECK (iratszam_tipus = ANY (ARRAY['befizetes'::text, 'kiadas'::text])),
  ev integer NOT NULL CHECK (ev >= 2000 AND ev <= 2100),
  next_szam integer NOT NULL DEFAULT 1 CHECK (next_szam >= 1),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT iratszam_pointers_pkey PRIMARY KEY (id),
  CONSTRAINT iratszam_pointers_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.jarulek_kedvezmeny (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  ev integer NOT NULL,
  tipus text NOT NULL CHECK (tipus = ANY (ARRAY['idoszak'::text, 'kor'::text, 'jovedelem'::text])),
  sorrend integer DEFAULT 0,
  aktiv boolean DEFAULT true,
  hatarid text,
  kedv_osszeg numeric,
  kor_tol integer,
  szazalek numeric,
  fix_osszeg numeric,
  jov_leiras text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jarulek_kedvezmeny_pkey PRIMARY KEY (id),
  CONSTRAINT jarulek_kedvezmeny_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.jegyzokonyv_hatarozatok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  jegyzokonyv_id uuid NOT NULL,
  napirendi_pont_id uuid,
  sorszam integer NOT NULL,
  ev integer NOT NULL,
  szoveg text NOT NULL,
  felelos text,
  hatarido date,
  allapot text DEFAULT 'elfogadva'::text,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT jegyzokonyv_hatarozatok_pkey PRIMARY KEY (id),
  CONSTRAINT jegyzokonyv_hatarozatok_jegyzokonyv_id_fkey FOREIGN KEY (jegyzokonyv_id) REFERENCES public.presbiteri_jegyzokonyvek(id),
  CONSTRAINT jegyzokonyv_hatarozatok_napirendi_pont_id_fkey FOREIGN KEY (napirendi_pont_id) REFERENCES public.jegyzokonyv_napirendi_pontok(id)
);
CREATE TABLE public.jegyzokonyv_napirendi_pontok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  jegyzokonyv_id uuid NOT NULL,
  sorszam integer NOT NULL,
  cim text NOT NULL,
  eloado text,
  targyalas text,
  szavazas_igen integer DEFAULT 0,
  szavazas_nem integer DEFAULT 0,
  szavazas_tartozkodo integer DEFAULT 0,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT jegyzokonyv_napirendi_pontok_pkey PRIMARY KEY (id),
  CONSTRAINT jegyzokonyv_napirendi_pontok_jegyzokonyv_id_fkey FOREIGN KEY (jegyzokonyv_id) REFERENCES public.presbiteri_jegyzokonyvek(id)
);
CREATE TABLE public.jegyzokonyv_resztvevok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  jegyzokonyv_id uuid NOT NULL,
  nev text NOT NULL,
  statusz text NOT NULL DEFAULT 'jelen'::text,
  szerep text,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT jegyzokonyv_resztvevok_pkey PRIMARY KEY (id),
  CONSTRAINT jegyzokonyv_resztvevok_jegyzokonyv_id_fkey FOREIGN KEY (jegyzokonyv_id) REFERENCES public.presbiteri_jegyzokonyvek(id)
);
CREATE TABLE public.keresztseg (
  id integer NOT NULL DEFAULT nextval('keresztseg_id_seq'::regclass),
  id_szemely integer NOT NULL,
  datum timestamp without time zone NOT NULL,
  lelkeszneve character varying,
  okirat character varying,
  keresztszulok character varying,
  megjegyzes character varying,
  munkanaploba boolean NOT NULL,
  helyid integer,
  congregation_id uuid,
  munkanaplo_id integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT keresztseg_pkey PRIMARY KEY (id),
  CONSTRAINT keresztseg_helyid_fk FOREIGN KEY (helyid) REFERENCES public.adrlocality(id),
  CONSTRAINT keresztseg_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT keresztseg_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.kiadas (
  id integer NOT NULL DEFAULT nextval('kiadas_id_seq'::regclass),
  xkey character varying NOT NULL,
  id_kiadascel integer NOT NULL,
  datum timestamp without time zone NOT NULL,
  osszeg numeric NOT NULL,
  nyugta text NOT NULL,
  iratszam text NOT NULL,
  irattipus text NOT NULL,
  megjegyzes text,
  created timestamp without time zone,
  deleted boolean NOT NULL,
  atvevo text,
  atvevoid integer,
  userid uuid NOT NULL,
  melleklet integer,
  congregation_id uuid,
  is_potlas boolean DEFAULT false,
  bankszamla_id integer,
  vonatkozo_idoszak character varying,
  belso_mozgas_xkey character varying,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  kedvezmenyezett_cui text,
  stornozott boolean NOT NULL DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_indok text,
  stornozott_by uuid,
  osszeg_ron numeric,
  arfolyam numeric,
  CONSTRAINT kiadas_pkey PRIMARY KEY (id),
  CONSTRAINT kiadas_atvevoid_fk FOREIGN KEY (atvevoid) REFERENCES public.szemely(id),
  CONSTRAINT kiadas_id_kiadascel_fk FOREIGN KEY (id_kiadascel) REFERENCES public.kiadascel(id),
  CONSTRAINT kiadas_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id),
  CONSTRAINT kiadas_userid_fk FOREIGN KEY (userid) REFERENCES auth.users(id),
  CONSTRAINT kiadas_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT kiadas_stornozott_by_fkey FOREIGN KEY (stornozott_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiadascel (
  id integer NOT NULL DEFAULT nextval('kiadascel_id_seq'::regclass),
  nevro character varying NOT NULL,
  nev character varying NOT NULL,
  id_szamadasicel character varying NOT NULL UNIQUE,
  aktiv boolean NOT NULL,
  belsotetel character varying,
  parentid integer,
  CONSTRAINT kiadascel_pkey PRIMARY KEY (id),
  CONSTRAINT kiadascel_parentid_fk FOREIGN KEY (parentid) REFERENCES public.kiadascel(id),
  CONSTRAINT kiadascel_id_szamadasicel_fk FOREIGN KEY (id_szamadasicel) REFERENCES public.szamadasicel(id)
);
CREATE TABLE public.kiadasikiseroiv (
  id integer NOT NULL DEFAULT nextval('kiadasikiseroiv_id_seq'::regclass),
  id_kiadas integer NOT NULL,
  iratszam integer NOT NULL,
  datum timestamp without time zone NOT NULL,
  megjegyzes character varying,
  created timestamp without time zone,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kiadasikiseroiv_pkey PRIMARY KEY (id),
  CONSTRAINT kiadasikiseroiv_id_kiadas_fk FOREIGN KEY (id_kiadas) REFERENCES public.kiadas(id)
);
CREATE TABLE public.kitert (
  id integer NOT NULL DEFAULT nextval('kitert_id_seq'::regclass),
  id_szemely integer NOT NULL,
  felekezet character varying,
  mikor timestamp without time zone,
  megjegyzes character varying,
  hovaid integer,
  congregation_id uuid,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kitert_pkey PRIMARY KEY (id),
  CONSTRAINT kitert_hovaid_fk FOREIGN KEY (hovaid) REFERENCES public.adrlocality(id),
  CONSTRAINT kitert_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT kitert_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.koltsegvetes (
  bealitasid character varying NOT NULL,
  szamadasicelid character varying NOT NULL,
  osszeg integer,
  congregation_id uuid NOT NULL,
  osszeg_modositott integer,
  osszeg_mod_2 numeric DEFAULT 0,
  osszeg_mod_3 numeric DEFAULT 0,
  osszeg_teny numeric DEFAULT 0,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT koltsegvetes_pkey PRIMARY KEY (bealitasid, szamadasicelid, congregation_id),
  CONSTRAINT koltsegvetes_szamadasicelid_fk FOREIGN KEY (szamadasicelid) REFERENCES public.szamadasicel(id),
  CONSTRAINT koltsegvetes_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.konfirmalas (
  id integer NOT NULL DEFAULT nextval('konfirmalas_id_seq'::regclass),
  id_szemely integer NOT NULL,
  datum date NOT NULL,
  lelkeszneve character varying,
  keresztelesideje date,
  megjegyzes character varying,
  helyid integer,
  congregation_id uuid,
  munkanaplo_id integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT konfirmalas_pkey PRIMARY KEY (id),
  CONSTRAINT konfirmalas_helyid_fk FOREIGN KEY (helyid) REFERENCES public.adrlocality(id),
  CONSTRAINT konfirmalas_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT konfirmalas_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.leltar_tetelek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  kategoria character varying NOT NULL,
  megnevezes character varying NOT NULL,
  leltari_szam character varying NOT NULL,
  helyszin character varying,
  felelos_szemely_id integer,
  felelos_neve character varying,
  beszerzes_datuma date,
  beszerzes_bizonylat character varying,
  beszerzesi_ertek numeric DEFAULT 0,
  mennyiseg numeric DEFAULT 1,
  mertekegyseg character varying DEFAULT 'db'::character varying,
  katalogus_kod character varying,
  hasznalati_ido_ev integer,
  torles_datuma date,
  torles_bizonylat character varying,
  torles_indoklasa character varying,
  is_deleted boolean DEFAULT false,
  megjegyzes text,
  created_at timestamp with time zone DEFAULT now(),
  userid uuid,
  szerzo character varying,
  regi_leltari_szam character varying,
  penzugy_xkey character varying,
  konyv_isbn character varying,
  konyv_kiado character varying,
  konyv_kiadas_helye character varying,
  konyv_kiadas_eve integer,
  konyv_terjedelem character varying,
  konyv_sorozatcim character varying,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leltar_tetelek_pkey PRIMARY KEY (id),
  CONSTRAINT leltar_tetelek_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT leltar_tetelek_felelos_fkey FOREIGN KEY (felelos_szemely_id) REFERENCES public.szemely(id),
  CONSTRAINT leltar_tetelek_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.licenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  congregation_id uuid,
  device_limit integer NOT NULL DEFAULT 2 CHECK (device_limit > 0 AND device_limit <= 10),
  valid_from date NOT NULL DEFAULT CURRENT_DATE,
  valid_until date NOT NULL,
  issued_jwt text NOT NULL,
  revoked boolean NOT NULL DEFAULT false,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  CONSTRAINT licenses_pkey PRIMARY KEY (id),
  CONSTRAINT licenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT licenses_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT licenses_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.logger (
  id integer NOT NULL DEFAULT nextval('logger_id_seq'::regclass),
  name character varying NOT NULL,
  operation character varying NOT NULL,
  changes text NOT NULL,
  tblname character varying,
  tblid character varying,
  username character varying NOT NULL,
  computer character varying NOT NULL,
  created timestamp without time zone NOT NULL,
  CONSTRAINT logger_pkey PRIMARY KEY (id)
);
CREATE TABLE public.material_movements (
  id bigint NOT NULL DEFAULT nextval('material_movements_id_seq'::regclass),
  material_id uuid NOT NULL,
  congregation_id uuid NOT NULL,
  datum date NOT NULL,
  tipus text NOT NULL CHECK (tipus = ANY (ARRAY['bevetel'::text, 'kiadas'::text])),
  mennyiseg numeric NOT NULL CHECK (mennyiseg > 0::numeric),
  ertek numeric NOT NULL DEFAULT 0,
  irat_szama text,
  magyarazat text,
  kapcsolt_kiadas_id bigint,
  kapcsolt_befizetes_id bigint,
  stornozott boolean NOT NULL DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_indok text,
  stornozott_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT material_movements_pkey PRIMARY KEY (id),
  CONSTRAINT material_movements_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id),
  CONSTRAINT material_movements_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT material_movements_kapcsolt_kiadas_id_fkey FOREIGN KEY (kapcsolt_kiadas_id) REFERENCES public.kiadas(id),
  CONSTRAINT material_movements_kapcsolt_befizetes_id_fkey FOREIGN KEY (kapcsolt_befizetes_id) REFERENCES public.befizetes(id),
  CONSTRAINT material_movements_stornozott_by_fkey FOREIGN KEY (stornozott_by) REFERENCES public.profiles(id),
  CONSTRAINT material_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_movements_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  nev text NOT NULL,
  megnevezes text,
  mertekegyseg text NOT NULL DEFAULT 'db'::text,
  egysegar numeric,
  kategoria text,
  aktiv boolean NOT NULL DEFAULT true,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT materials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.mm_bookmarks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  otlet_id uuid,
  segedanyag_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT mm_bookmarks_pkey PRIMARY KEY (id),
  CONSTRAINT mm_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT mm_bookmarks_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_bookmarks_segedanyag_id_fkey FOREIGN KEY (segedanyag_id) REFERENCES public.mm_segedanyagok(id)
);
CREATE TABLE public.mm_dokumentumok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  nev text NOT NULL,
  url text NOT NULL,
  meret integer DEFAULT 0,
  tipus text,
  feltolto_id uuid NOT NULL,
  feltolto_nev text,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mm_dokumentumok_pkey PRIMARY KEY (id),
  CONSTRAINT mm_dokumentumok_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_dokumentumok_feltolto_id_fkey FOREIGN KEY (feltolto_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_feladatok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  cim text NOT NULL,
  leiras text,
  felelos_id uuid,
  felelos_nev text,
  hatarido date,
  statusz text DEFAULT 'fuggeben'::text CHECK (statusz = ANY (ARRAY['fuggeben'::text, 'folyamatban'::text, 'kesz'::text])),
  sorrend integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mm_feladatok_pkey PRIMARY KEY (id),
  CONSTRAINT mm_feladatok_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_feladatok_felelos_id_fkey FOREIGN KEY (felelos_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_felhasznalo_jelveny (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  jelveny_id integer NOT NULL,
  elnyerve timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_felhasznalo_jelveny_pkey PRIMARY KEY (id),
  CONSTRAINT mm_felhasznalo_jelveny_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT mm_felhasznalo_jelveny_jelveny_id_fkey FOREIGN KEY (jelveny_id) REFERENCES public.mm_jelveny_tipusok(id)
);
CREATE TABLE public.mm_felhasznalo_statisztika (
  user_id uuid NOT NULL,
  otletek_szama integer DEFAULT 0,
  elfogadott_otletek integer DEFAULT 0,
  megvalosult_otletek integer DEFAULT 0,
  tamogatasok_adva integer DEFAULT 0,
  hozzaszolasok_szama integer DEFAULT 0,
  segedanyagok_feltoltve integer DEFAULT 0,
  feladatok_teljesitve integer DEFAULT 0,
  ertekelesek_adva integer DEFAULT 0,
  osszpontszam integer DEFAULT 0,
  szint text DEFAULT 'Újonc'::text,
  frissitve timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_felhasznalo_statisztika_pkey PRIMARY KEY (user_id),
  CONSTRAINT mm_felhasznalo_statisztika_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_hozzaszolasok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_nev text,
  user_gyulekezet text,
  szoveg text NOT NULL,
  szulo_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_hozzaszolasok_pkey PRIMARY KEY (id),
  CONSTRAINT mm_hozzaszolasok_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_hozzaszolasok_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT mm_hozzaszolasok_szulo_id_fkey FOREIGN KEY (szulo_id) REFERENCES public.mm_hozzaszolasok(id)
);
CREATE TABLE public.mm_jelveny_tipusok (
  id integer NOT NULL DEFAULT nextval('mm_jelveny_tipusok_id_seq'::regclass),
  kod text NOT NULL UNIQUE,
  nev text NOT NULL,
  leiras text NOT NULL,
  feltetel text NOT NULL,
  ikon text NOT NULL,
  szin text DEFAULT '#f59f00'::text,
  sorrend integer DEFAULT 0,
  CONSTRAINT mm_jelveny_tipusok_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mm_kategoriak (
  id integer NOT NULL DEFAULT nextval('mm_kategoriak_id_seq'::regclass),
  nev text NOT NULL UNIQUE,
  ikon text NOT NULL,
  szin text DEFAULT '#206bc4'::text,
  leiras text,
  sorrend integer DEFAULT 0,
  CONSTRAINT mm_kategoriak_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mm_merfoldkovek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  cim text NOT NULL,
  leiras text,
  hatarido date,
  teljesitve boolean DEFAULT false,
  teljesitve_datum timestamp with time zone,
  sorrend integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mm_merfoldkovek_pkey PRIMARY KEY (id),
  CONSTRAINT mm_merfoldkovek_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id)
);
CREATE TABLE public.mm_otlet_cimkek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  cimke text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_otlet_cimkek_pkey PRIMARY KEY (id),
  CONSTRAINT mm_otlet_cimkek_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id)
);
CREATE TABLE public.mm_otlet_kategoriak (
  otlet_id uuid NOT NULL,
  kategoria_id integer NOT NULL,
  CONSTRAINT mm_otlet_kategoriak_pkey PRIMARY KEY (otlet_id, kategoria_id),
  CONSTRAINT mm_otlet_kategoriak_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_otlet_kategoriak_kategoria_id_fkey FOREIGN KEY (kategoria_id) REFERENCES public.mm_kategoriak(id)
);
CREATE TABLE public.mm_otletek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cim text NOT NULL,
  leiras text NOT NULL,
  celcsoport text DEFAULT 'Mindenki'::text CHECK (celcsoport = ANY (ARRAY['Fiatalok'::text, 'Felnőttek'::text, 'Idősek'::text, 'Családok'::text, 'Gyerekek'::text, 'Mindenki'::text])),
  becsult_ido text DEFAULT '2-3 hónap'::text CHECK (becsult_ido = ANY (ARRAY['1 hónap'::text, '2-3 hónap'::text, 'Fél év'::text, 'Folyamatos'::text])),
  statusz text DEFAULT 'uj'::text CHECK (statusz = ANY (ARRAY['uj'::text, 'szavazas'::text, 'kozos_munka'::text, 'megvalosult'::text, 'archivalt'::text, 'piszkozat'::text])),
  szavazas_kezdete timestamp with time zone,
  szavazas_vege timestamp with time zone,
  tamogatasok_szama integer DEFAULT 0,
  csatlakozok_szama integer DEFAULT 0,
  hozzaszolasok_szama integer DEFAULT 0,
  kidolgozottsag integer DEFAULT 0,
  benyujtas_szama integer DEFAULT 1,
  otletgazda_id uuid NOT NULL,
  otletgazda_nev text,
  otletgazda_gyulekezet text,
  csatolmany_url text,
  aktiv boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT mm_otletek_pkey PRIMARY KEY (id),
  CONSTRAINT mm_otletek_otletgazda_id_fkey FOREIGN KEY (otletgazda_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_segedanyag_ertekelesek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  segedanyag_id uuid NOT NULL,
  user_id uuid NOT NULL,
  pontszam integer NOT NULL CHECK (pontszam >= 1 AND pontszam <= 5),
  velemeny text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_segedanyag_ertekelesek_pkey PRIMARY KEY (id),
  CONSTRAINT mm_segedanyag_ertekelesek_segedanyag_id_fkey FOREIGN KEY (segedanyag_id) REFERENCES public.mm_segedanyagok(id),
  CONSTRAINT mm_segedanyag_ertekelesek_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_segedanyag_kategoriak (
  segedanyag_id uuid NOT NULL,
  kategoria_id integer NOT NULL,
  CONSTRAINT mm_segedanyag_kategoriak_pkey PRIMARY KEY (segedanyag_id, kategoria_id),
  CONSTRAINT mm_segedanyag_kategoriak_segedanyag_id_fkey FOREIGN KEY (segedanyag_id) REFERENCES public.mm_segedanyagok(id),
  CONSTRAINT mm_segedanyag_kategoriak_kategoria_id_fkey FOREIGN KEY (kategoria_id) REFERENCES public.mm_kategoriak(id)
);
CREATE TABLE public.mm_segedanyagok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cim text NOT NULL,
  leiras text,
  forras_url text,
  forras_nev text,
  formatum text DEFAULT 'PDF'::text CHECK (formatum = ANY (ARRAY['PDF'::text, 'DOCX'::text, 'PPTX'::text, 'video'::text, 'link'::text, 'csomag'::text])),
  feltolto_id uuid NOT NULL,
  feltolto_nev text,
  feltolto_gyulekezet text,
  letoltes_szam integer DEFAULT 0,
  atlag_ertekeles numeric DEFAULT 0,
  ertekelesek_szama integer DEFAULT 0,
  csatolmany_url text,
  aktiv boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_segedanyagok_pkey PRIMARY KEY (id),
  CONSTRAINT mm_segedanyagok_feltolto_id_fkey FOREIGN KEY (feltolto_id) REFERENCES auth.users(id)
);
CREATE TABLE public.mm_szavazatok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  otlet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tipus text NOT NULL CHECK (tipus = ANY (ARRAY['tamogatas'::text, 'csatlakozas'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mm_szavazatok_pkey PRIMARY KEY (id),
  CONSTRAINT mm_szavazatok_otlet_id_fkey FOREIGN KEY (otlet_id) REFERENCES public.mm_otletek(id),
  CONSTRAINT mm_szavazatok_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.monetar (
  id integer NOT NULL DEFAULT nextval('monetar_id_seq'::regclass),
  cimlet_id integer NOT NULL,
  darab integer NOT NULL,
  source character varying,
  sourceid character varying,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT monetar_pkey PRIMARY KEY (id),
  CONSTRAINT monetar_cimlet_id_fk FOREIGN KEY (cimlet_id) REFERENCES public.nom_cimlet(id)
);
CREATE TABLE public.munkanaplo (
  id integer NOT NULL DEFAULT nextval('munkanaplo_id_seq'::regclass),
  idopont date,
  jellege character varying,
  id_jellege character varying,
  bibliaolvasas character varying,
  alapige character varying,
  cim character varying,
  enekek character varying,
  jelenlet_ferfi integer,
  jelenlet_no integer,
  jelenlet_gyermek integer,
  szolgalt character varying,
  persely numeric,
  megjegyzes text,
  created timestamp without time zone,
  jelenlet_osszesen integer NOT NULL,
  mediapath character varying,
  congregation_id uuid,
  kategoria character varying DEFAULT 'szolgalat'::character varying,
  du boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT munkanaplo_pkey PRIMARY KEY (id),
  CONSTRAINT munkanaplo_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.nevnap (
  id integer NOT NULL,
  honap character varying,
  nap character varying,
  nev1 character varying NOT NULL,
  nev2 character varying,
  nev3 character varying,
  CONSTRAINT nevnap_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nom_cimlet (
  id integer NOT NULL DEFAULT nextval('nom_cimlet_id_seq'::regclass),
  name character varying NOT NULL,
  val integer NOT NULL,
  divide integer NOT NULL,
  deleted boolean NOT NULL,
  CONSTRAINT nom_cimlet_pkey PRIMARY KEY (id)
);
CREATE TABLE public.oblio_fiokok (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  api_secret_encrypted text NOT NULL,
  cif text NOT NULL,
  sorozat_default text,
  nev_default_service text DEFAULT 'Chirie spațiu'::text,
  aktiv boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  utolso_token text,
  utolso_token_expires_at timestamp with time zone,
  utolso_teszt_at timestamp with time zone,
  utolso_teszt_ok boolean,
  utolso_teszt_hiba text,
  chitanta_sorozat_default text,
  chitanta_kovetkezo_szam integer DEFAULT 1,
  utolso_xml_letoltes_at timestamp with time zone,
  CONSTRAINT oblio_fiokok_pkey PRIMARY KEY (id),
  CONSTRAINT oblio_fiokok_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.oblio_kiadas_match (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  kiadas_id integer NOT NULL,
  anaf_uuid text NOT NULL,
  supplier_cui text,
  supplier_name text,
  invoice_number text,
  invoice_date date,
  invoice_amount numeric,
  local_file_relpath text,
  match_method text NOT NULL DEFAULT 'manual'::text CHECK (match_method = ANY (ARRAY['auto_cui'::text, 'auto_name_amount_date'::text, 'manual'::text])),
  match_confidence text DEFAULT 'medium'::text CHECK (match_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  manual_note text,
  matched_at timestamp with time zone NOT NULL DEFAULT now(),
  matched_by uuid,
  CONSTRAINT oblio_kiadas_match_pkey PRIMARY KEY (id),
  CONSTRAINT oblio_kiadas_match_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT oblio_kiadas_match_kiadas_id_fkey FOREIGN KEY (kiadas_id) REFERENCES public.kiadas(id),
  CONSTRAINT oblio_kiadas_match_matched_by_fkey FOREIGN KEY (matched_by) REFERENCES auth.users(id)
);
CREATE TABLE public.oblio_szamlak (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  oblio_fiok_id uuid,
  berleti_szerzodes_id uuid,
  befizetes_id integer,
  tipus text NOT NULL DEFAULT 'e_factura'::text CHECK (tipus = ANY (ARRAY['e_factura'::text, 'chitanta_papir'::text])),
  sorozat text NOT NULL,
  szam integer NOT NULL,
  szamla_datum date NOT NULL DEFAULT CURRENT_DATE,
  esedekesseg date,
  klienesseg_nev text NOT NULL,
  klienesseg_cui text,
  klienesseg_cim text,
  osszeg_net numeric NOT NULL,
  osszeg_tva numeric DEFAULT 0,
  osszeg_brut numeric NOT NULL,
  pénznem text DEFAULT 'RON'::text,
  oblio_invoice_id text,
  pdf_url text,
  pdf_local_path text,
  e_factura_uuid text,
  e_factura_status text DEFAULT 'nepreluat'::text CHECK (e_factura_status IS NULL OR (e_factura_status = ANY (ARRAY['nepreluat'::text, 'in_prelucrare'::text, 'ok'::text, 'nok'::text, 'not_applicable'::text]))),
  chitanta_pdf_html text,
  e_factura_errors jsonb,
  utolso_szinkronizalas_at timestamp with time zone,
  collected_at timestamp with time zone,
  stornozott boolean DEFAULT false,
  stornozott_at timestamp with time zone,
  stornozott_indok text,
  megjegyzes text,
  issued_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reprezentand text,
  tomb_id uuid,
  nyomdai_szam integer,
  gyulekezeti_szam integer,
  klienesseg_nr_orc_an text,
  reprezentand_ro text,
  CONSTRAINT oblio_szamlak_pkey PRIMARY KEY (id),
  CONSTRAINT oblio_szamlak_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT oblio_szamlak_oblio_fiok_id_fkey FOREIGN KEY (oblio_fiok_id) REFERENCES public.oblio_fiokok(id),
  CONSTRAINT oblio_szamlak_berleti_szerzodes_id_fkey FOREIGN KEY (berleti_szerzodes_id) REFERENCES public.berleti_szerzodes(id),
  CONSTRAINT oblio_szamlak_befizetes_id_fkey FOREIGN KEY (befizetes_id) REFERENCES public.befizetes(id),
  CONSTRAINT oblio_szamlak_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES auth.users(id),
  CONSTRAINT oblio_szamlak_tomb_id_fkey FOREIGN KEY (tomb_id) REFERENCES public.chitanta_tombok(id)
);
CREATE TABLE public.pastor_profiles (
  user_id uuid NOT NULL,
  display_title text,
  photo_url text,
  address text,
  emergency_phone text,
  service_started_at date,
  previous_service_places ARRAY DEFAULT '{}'::text[],
  previous_roles ARRAY DEFAULT '{}'::text[],
  bio text,
  ministry_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pastor_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT pastor_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.presbiter (
  id integer NOT NULL DEFAULT nextval('presbiter_id_seq'::regclass),
  id_szemely integer NOT NULL,
  tisztseg character varying NOT NULL,
  korzet character varying,
  korzetszamok character varying,
  id_csoport integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT presbiter_pkey PRIMARY KEY (id),
  CONSTRAINT presbiter_id_csoport_fk FOREIGN KEY (id_csoport) REFERENCES public.csoport(id),
  CONSTRAINT presbiter_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id)
);
CREATE TABLE public.presbiteri_jegyzokonyvek (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  tipus text NOT NULL DEFAULT 'presbiteri'::text,
  ev integer NOT NULL,
  ules_sorszam integer NOT NULL,
  datum date NOT NULL,
  hely text,
  kezdes text,
  zaras text,
  hatarozatkepesseg boolean DEFAULT true,
  elnok_neve text,
  jegyzo_neve text,
  hitelesito1 text,
  hitelesito2 text,
  allapot text NOT NULL DEFAULT 'draft'::text,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  igevers text,
  felolvasas text,
  revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT presbiteri_jegyzokonyvek_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profile_congregations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  congregation_id uuid NOT NULL,
  role_scope text NOT NULL DEFAULT 'konyvelo'::text CHECK (role_scope = ANY (ARRAY['konyvelo'::text, 'egyhazmegyei_szamvevo'::text])),
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT false,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  revoked_reason text,
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'revoked'::text])),
  approval_reason text,
  approved_at timestamp with time zone,
  approved_by uuid,
  CONSTRAINT profile_congregations_pkey PRIMARY KEY (id),
  CONSTRAINT profile_congregations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_congregations_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT profile_congregations_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id),
  CONSTRAINT profile_congregations_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id),
  CONSTRAINT profile_congregations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profile_preferences (
  user_id uuid NOT NULL,
  default_dashboard text NOT NULL DEFAULT 'auto'::text CHECK (default_dashboard = ANY (ARRAY['auto'::text, 'gyulekezet'::text, 'egyhazmegye'::text, 'egyhazkerulet'::text, 'admin'::text])),
  last_used_scope text,
  last_used_scope_id uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT profile_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profile_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  scope text NOT NULL CHECK (scope = ANY (ARRAY['system'::text, 'district'::text, 'diocese'::text, 'congregation'::text])),
  scope_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'egyhazkeruleti_admin'::text, 'egyhazmegyei_admin'::text, 'esperes'::text, 'egyhazmegyei_szamvevo'::text, 'lelkesz'::text, 'konyvelo'::text, 'custom'::text])),
  custom_label text,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  approval_status text NOT NULL DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'revoked'::text])),
  approval_reason text,
  granted_by uuid,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  revoked_by uuid,
  revoked_at timestamp with time zone,
  revoked_reason text,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT profile_roles_pkey PRIMARY KEY (id),
  CONSTRAINT profile_roles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  congregation text,
  birth_date date,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  phone text,
  congregation_id uuid,
  role text DEFAULT 'lelkesz'::text CHECK (role = ANY (ARRAY['lelkesz'::text, 'esperes'::text, 'egyhazmegyei_admin'::text, 'egyhazkeruleti_admin'::text, 'admin'::text, 'konyvelo'::text, 'egyhazmegyei_szamvevo'::text])),
  diocese_id uuid,
  district_id uuid,
  walkthrough_completed boolean NOT NULL DEFAULT false,
  walkthrough_skipped_at timestamp with time zone,
  onboarding_completed_at timestamp with time zone,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT profiles_diocese_id_fkey FOREIGN KEY (diocese_id) REFERENCES public.dioceses(id),
  CONSTRAINT profiles_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.public_magazine_issues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  magazine_id uuid NOT NULL,
  congregation_id uuid NOT NULL,
  issue_number text NOT NULL,
  title text,
  cover_image_url text,
  pdf_url text NOT NULL,
  published_at date,
  notes text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_magazine_issues_pkey PRIMARY KEY (id),
  CONSTRAINT public_magazine_issues_magazine_id_fkey FOREIGN KEY (magazine_id) REFERENCES public.public_magazines(id),
  CONSTRAINT public_magazine_issues_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.public_magazines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  cover_image_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_magazines_pkey PRIMARY KEY (id),
  CONSTRAINT public_magazines_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.public_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  author_id uuid,
  slug text NOT NULL CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,127}[a-z0-9]?$'::text),
  title text NOT NULL,
  excerpt text,
  cover_image_url text,
  body_markdown text,
  body_html text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_posts_pkey PRIMARY KEY (id),
  CONSTRAINT public_posts_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT public_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.public_site_themes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  preset_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  colors jsonb NOT NULL,
  typography jsonb NOT NULL,
  hero_style text NOT NULL DEFAULT 'photo'::text CHECK (hero_style = ANY (ARRAY['photo'::text, 'pattern'::text, 'crest'::text, 'gradient'::text])),
  border_radius text NOT NULL DEFAULT '1rem'::text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_site_themes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.public_sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,58}[a-z0-9]$'::text),
  display_name text NOT NULL,
  tagline text,
  hero_image_url text,
  crest_image_url text,
  theme_id uuid,
  custom_primary_color text CHECK (custom_primary_color IS NULL OR custom_primary_color ~ '^#[0-9a-fA-F]{6}$'::text),
  custom_accent_color text CHECK (custom_accent_color IS NULL OR custom_accent_color ~ '^#[0-9a-fA-F]{6}$'::text),
  contact_email text,
  contact_phone text,
  address text,
  about_html text,
  is_published boolean NOT NULL DEFAULT false,
  robots_index boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  show_member_count boolean NOT NULL DEFAULT false,
  show_presbyter_count boolean NOT NULL DEFAULT false,
  show_family_count boolean NOT NULL DEFAULT false,
  show_age_distribution boolean NOT NULL DEFAULT false,
  override_member_count integer,
  override_presbyter_count integer,
  override_family_count integer,
  CONSTRAINT public_sites_pkey PRIMARY KEY (id),
  CONSTRAINT public_sites_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT public_sites_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.public_site_themes(id)
);
CREATE TABLE public.sirhely (
  id integer NOT NULL DEFAULT nextval('sirhely_id_seq'::regclass),
  parcella character varying NOT NULL,
  sor integer NOT NULL,
  szam character varying NOT NULL,
  elhelyezkedes character varying,
  meret character varying,
  tipus character varying,
  megjegyzes character varying,
  aktivberlesid integer,
  temetoid integer NOT NULL,
  imagelnk character varying,
  allapot text DEFAULT 'szabad'::text CHECK (allapot = ANY (ARRAY['szabad'::text, 'foglalt'::text, 'lejart'::text, 'zart'::text, 'fenntartott'::text])),
  gps_lat double precision,
  gps_lng double precision,
  deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sirhely_pkey PRIMARY KEY (id),
  CONSTRAINT sirhely_aktivberlesid_fk FOREIGN KEY (aktivberlesid) REFERENCES public.sirhelyberles(id),
  CONSTRAINT sirhely_temetoid_fk FOREIGN KEY (temetoid) REFERENCES public.sirhelytemeto(id)
);
CREATE TABLE public.sirhelyberles (
  id integer NOT NULL DEFAULT nextval('sirhelyberles_id_seq'::regclass),
  sirhelyid integer NOT NULL,
  befizetesid integer,
  megvaltas timestamp without time zone NOT NULL,
  lejarata timestamp without time zone,
  megjegyzes character varying,
  berlo character varying,
  berloid integer,
  berlocim character varying,
  berloelerhetoseg character varying,
  tipus text DEFAULT 'berles'::text CHECK (tipus = ANY (ARRAY['berles'::text, 'megvaltas'::text])),
  osszeg numeric,
  deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sirhelyberles_pkey PRIMARY KEY (id),
  CONSTRAINT sirhelyberles_befizetesid_fk FOREIGN KEY (befizetesid) REFERENCES public.befizetes(id),
  CONSTRAINT sirhelyberles_berloid_fk FOREIGN KEY (berloid) REFERENCES public.szemely(id),
  CONSTRAINT sirhelyberles_sirhelyid_fk FOREIGN KEY (sirhelyid) REFERENCES public.sirhely(id)
);
CREATE TABLE public.sirhelyelhunyt (
  id integer NOT NULL DEFAULT nextval('sirhelyelhunyt_id_seq'::regclass),
  temetesid integer,
  sz_datum timestamp without time zone,
  sz_hely character varying,
  ferfi boolean,
  anyjaneve character varying,
  hdatum timestamp without time zone,
  hhely character varying,
  tdatum timestamp without time zone,
  ttipus character varying,
  tmodja character varying,
  elhelyezkedes character varying,
  temetteto character varying,
  szolgaltato character varying,
  megjegyzes character varying,
  nev character varying,
  sznev character varying,
  sirhelyid integer NOT NULL,
  deleted boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sirhelyelhunyt_pkey PRIMARY KEY (id),
  CONSTRAINT sirhelyelhunyt_temetesid_fk FOREIGN KEY (temetesid) REFERENCES public.temetes(id),
  CONSTRAINT sirhelyelhunyt_sirhelyid_fk FOREIGN KEY (sirhelyid) REFERENCES public.sirhely(id)
);
CREATE TABLE public.sirhelytemeto (
  id integer NOT NULL DEFAULT nextval('sirhelytemeto_id_seq'::regclass),
  nev character varying NOT NULL,
  megjegyzes character varying,
  congregation_id uuid,
  cim text,
  aktiv boolean DEFAULT true,
  deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sirhelytemeto_pkey PRIMARY KEY (id),
  CONSTRAINT sirhelytemeto_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.support_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid,
  user_id uuid,
  sender_name text,
  sender_email text,
  category text NOT NULL CHECK (category = ANY (ARRAY['hiba'::text, 'fejlesztes'::text, 'kiegeszites'::text, 'kerdes'::text, 'egyeb'::text])),
  module text,
  subject text NOT NULL,
  message text NOT NULL,
  urgency text DEFAULT 'alacsony'::text CHECK (urgency = ANY (ARRAY['alacsony'::text, 'kozepes'::text, 'surgos'::text])),
  page_url text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'read'::text, 'replied'::text, 'closed'::text])),
  admin_reply text,
  replied_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_messages_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.system_broadcasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sent_by uuid NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  cim text NOT NULL,
  uzenet text NOT NULL,
  tipus text NOT NULL DEFAULT 'info'::text CHECK (tipus = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'danger'::text, 'release'::text])),
  hivatkozas text,
  target_scope text NOT NULL CHECK (target_scope = ANY (ARRAY['all'::text, 'role'::text, 'congregation'::text, 'diocese'::text, 'district'::text])),
  target_role text,
  target_congregation_ids ARRAY,
  target_diocese_ids ARRAY,
  target_district_ids ARRAY,
  send_email boolean NOT NULL DEFAULT false,
  email_sent_at timestamp with time zone,
  email_error text,
  recipient_count integer NOT NULL DEFAULT 0,
  release_version text,
  release_category text CHECK (release_category IS NULL OR (release_category = ANY (ARRAY['bugfix'::text, 'feature'::text, 'improvement'::text, 'security'::text, 'breaking'::text]))),
  release_changelog_key text UNIQUE,
  CONSTRAINT system_broadcasts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_finance_costs (
  id bigint NOT NULL DEFAULT nextval('system_finance_costs_id_seq'::regclass),
  kategoria text NOT NULL CHECK (kategoria = ANY (ARRAY['supabase'::text, 'railway'::text, 'vercel'::text, 'email_service'::text, 'storage'::text, 'ai_gpu'::text, 'ai_proxy'::text, 'ai_monitoring'::text, 'mobile'::text, 'monitoring'::text, 'domain'::text, 'egyszeri'::text, 'egyeb'::text])),
  nev text NOT NULL,
  havi_usd numeric NOT NULL DEFAULT 0,
  havi_ron numeric,
  arfolyam_usd numeric DEFAULT 4.41,
  aktiv boolean NOT NULL DEFAULT true,
  sorszam integer NOT NULL DEFAULT 0,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_finance_costs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_pricing_tiers (
  id bigint NOT NULL DEFAULT nextval('system_pricing_tiers_id_seq'::regclass),
  nev text NOT NULL,
  tipus text NOT NULL DEFAULT 'gyulekezet'::text CHECK (tipus = ANY (ARRAY['gyulekezet'::text, 'egyhazmegye'::text, 'teszt'::text, 'kedvezmeny'::text])),
  min_tagok integer NOT NULL DEFAULT 0,
  max_tagok integer,
  havi_dij_ron numeric NOT NULL DEFAULT 0,
  eves_dij_ron numeric NOT NULL DEFAULT 0,
  aktiv boolean NOT NULL DEFAULT true,
  sorszam integer NOT NULL DEFAULT 0,
  megjegyzes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_pricing_tiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_settings_pkey PRIMARY KEY (key),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.szamadasicel (
  id character varying NOT NULL,
  nevro character varying,
  nev character varying,
  sorszam integer NOT NULL,
  sorszamok character varying,
  aktiv boolean NOT NULL,
  aktivevi boolean NOT NULL,
  iscel boolean NOT NULL,
  belsotetel character varying,
  type character varying NOT NULL,
  tva_plafonba_szamit boolean NOT NULL DEFAULT false,
  tva_mentesseg_hivatkozas text,
  szint text NOT NULL DEFAULT 'gyulekezet'::text CHECK (szint = ANY (ARRAY['gyulekezet'::text, 'egyhazmegye'::text, 'kerulet'::text])),
  CONSTRAINT szamadasicel_pkey PRIMARY KEY (id)
);
CREATE TABLE public.szemely (
  id integer NOT NULL DEFAULT nextval('szemely_id_seq'::regclass),
  cnp character varying NOT NULL,
  szcs_nev character varying,
  k_nev character varying,
  csaladnev character varying,
  ferjk_nev character varying,
  allapot character varying,
  apjaneve character varying,
  id_apja character varying,
  anyjaneve character varying,
  id_anyja character varying,
  csaladfo boolean NOT NULL,
  ferfi boolean NOT NULL,
  meghalt boolean NOT NULL,
  sz_datum date,
  sz_helyid integer,
  vallas character varying,
  foglalkozas character varying,
  nemzetiseg character varying,
  c_utcaid integer NOT NULL,
  c_szam character varying,
  c_tombhaz character varying,
  c_lepcsohaz character varying,
  c_ajto character varying,
  c_emelet character varying,
  c_szcim character varying,
  telefon character varying,
  email character varying,
  befizetoev integer NOT NULL,
  megjegyzes character varying,
  isvisible boolean NOT NULL,
  kep character varying,
  type character varying NOT NULL,
  created timestamp without time zone,
  namepattern character varying,
  szig character varying,
  taj character varying,
  congregation_id uuid,
  family_id uuid,
  member_status text DEFAULT 'aktív'::text,
  voter_eligible boolean DEFAULT false,
  photo_url text,
  c_helysegid integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT szemely_pkey PRIMARY KEY (id),
  CONSTRAINT szemely_c_utcaid_fk FOREIGN KEY (c_utcaid) REFERENCES public.adrstreet(id),
  CONSTRAINT szemely_sz_helyid_fk FOREIGN KEY (sz_helyid) REFERENCES public.adrlocality(id),
  CONSTRAINT szemely_id_apja_fk FOREIGN KEY (id_apja) REFERENCES public.szemely(cnp),
  CONSTRAINT szemely_id_anyja_fk FOREIGN KEY (id_anyja) REFERENCES public.szemely(cnp),
  CONSTRAINT szemely_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT szemely_c_helysegid_fk FOREIGN KEY (c_helysegid) REFERENCES public.adrlocality(id)
);
CREATE TABLE public.temetes (
  id integer NOT NULL DEFAULT nextval('temetes_id_seq'::regclass),
  id_szemely integer NOT NULL,
  hdatum timestamp without time zone NOT NULL,
  hoka character varying,
  tdatum timestamp without time zone NOT NULL,
  lelkeszneve character varying,
  okirat character varying,
  megjegyzes character varying,
  munkanaploba boolean NOT NULL,
  hhelyid integer,
  thelyid integer,
  congregation_id uuid,
  munkanaplo_id integer,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT temetes_pkey PRIMARY KEY (id),
  CONSTRAINT temetes_id_szemely_fk FOREIGN KEY (id_szemely) REFERENCES public.szemely(id),
  CONSTRAINT temetes_hhelyid_fk FOREIGN KEY (hhelyid) REFERENCES public.adrlocality(id),
  CONSTRAINT temetes_thelyid_fk FOREIGN KEY (thelyid) REFERENCES public.adrlocality(id),
  CONSTRAINT temetes_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  account_code text NOT NULL,
  direction text CHECK (direction = ANY (ARRAY['income'::text, 'expense'::text])),
  amount_ron numeric NOT NULL,
  payment_type text DEFAULT 'cash'::text,
  document_number text,
  description text,
  entered_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT transactions_entered_by_fkey FOREIGN KEY (entered_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_fingerprint text NOT NULL,
  device_name text,
  platform text NOT NULL,
  public_key bytea NOT NULL,
  registered_at timestamp with time zone NOT NULL DEFAULT now(),
  last_seen timestamp with time zone,
  revoked boolean NOT NULL DEFAULT false,
  revoked_by uuid,
  revoked_at timestamp with time zone,
  revoke_reason text,
  CONSTRAINT user_devices_pkey PRIMARY KEY (id),
  CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_devices_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.valuta_atert (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  congregation_id uuid NOT NULL,
  bankszamla_id integer NOT NULL,
  ev integer NOT NULL,
  valuta character varying NOT NULL,
  deviza_egyenleg numeric NOT NULL,
  regi_arfolyam numeric,
  regi_ron_ertek numeric NOT NULL,
  uj_arfolyam numeric NOT NULL,
  uj_ron_ertek numeric NOT NULL,
  kulonbozet numeric NOT NULL,
  tipus text NOT NULL CHECK (tipus = ANY (ARRAY['nyereseg'::text, 'veszteseg'::text, 'nulla'::text])),
  arfolyam_datum date NOT NULL DEFAULT CURRENT_DATE,
  arfolyam_forras character varying NOT NULL DEFAULT 'BNR'::character varying,
  befizetes_id bigint,
  kiadas_id bigint,
  megjegyzes text,
  userid uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  deleted boolean DEFAULT false,
  revision bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT valuta_atert_pkey PRIMARY KEY (id),
  CONSTRAINT valuta_atert_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id),
  CONSTRAINT valuta_atert_bankszamla_id_fkey FOREIGN KEY (bankszamla_id) REFERENCES public.bankszamlak(id),
  CONSTRAINT valuta_atert_befizetes_id_fkey FOREIGN KEY (befizetes_id) REFERENCES public.befizetes(id),
  CONSTRAINT valuta_atert_kiadas_id_fkey FOREIGN KEY (kiadas_id) REFERENCES public.kiadas(id),
  CONSTRAINT valuta_atert_userid_fkey FOREIGN KEY (userid) REFERENCES auth.users(id)
);
CREATE TABLE public.wizard_progress (
  user_id uuid NOT NULL,
  current_step smallint NOT NULL DEFAULT 1 CHECK (current_step >= 1 AND current_step <= 5),
  completed_steps ARRAY NOT NULL DEFAULT ARRAY[]::smallint[],
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wizard_progress_pkey PRIMARY KEY (user_id),
  CONSTRAINT wizard_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);